import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Supported languages with their native names
export const LANGUAGES = {
    en: { name: 'English', native: 'English', flag: '🇺🇸' },
    hi: { name: 'Hindi', native: 'हिंदी', flag: '🇮🇳' },
    ta: { name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
    te: { name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
    bn: { name: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
    mr: { name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
    kn: { name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
    es: { name: 'Spanish', native: 'Español', flag: '🇪🇸' },
    fr: { name: 'French', native: 'Français', flag: '🇫🇷' },
    zh: { name: 'Chinese', native: '中文', flag: '🇨🇳' },
    ar: { name: 'Arabic', native: 'العربية', flag: '🇸🇦' },
} as const;

export type LanguageCode = keyof typeof LANGUAGES;

// Translation keys
export interface Translations {
    // Header
    appName: string;
    realTimeAirQuality: string;

    // Location
    gps: string;
    defaultLocation: string;
    locateMe: string;
    currentLocation: string;

    // AQI Card
    airQualityIndex: string;
    good: string;
    moderate: string;
    unhealthyForSensitive: string;
    unhealthy: string;
    veryUnhealthy: string;
    hazardous: string;

    // Health Messages
    healthMsgGood: string;
    healthMsgModerate: string;
    healthMsgSensitive: string;
    healthMsgUnhealthy: string;
    healthMsgHazardous: string;

    // Weather Card
    weatherConditions: string;
    humidity: string;
    wind: string;
    pressure: string;
    dry: string;
    comfort: string;
    humid: string;

    // PM Card
    particulateMatter: string;
    fine: string;
    coarse: string;
    excellentAir: string;
    acceptableAir: string;
    wearMask: string;
    avoidOutdoor: string;

    // Forecast
    todayForecast: string;
    fiveDayForecast: string;

    // Actions
    settings: string;
    help: string;
    analysis: string;
    history: string;
    search: string;
    searchPlaceholder: string;

    // Data Status
    liveData: string;
    apiSources: string;
    updatedNow: string;

    // Indian Cities
    indianCities: string;

    // Recommendations
    recommendations: string;
    whatToDo: string;
    whatToAvoid: string;

    // ML Insights
    mlInsights: string;
    aiPowered: string;

    // Gas Levels
    gasLevels: string;

    // Language
    selectLanguage: string;

    // New Optional Keys
    cityLucknow?: string;
    cityNagpur?: string;
    cityKanpur?: string;
    cityJaipur?: string;

    weatherClear?: string;  // Clear sky
    weatherClouds?: string; // Clouds
    weatherRain?: string;   // Rain
    weatherDrizzle?: string;
    weatherThunderstorm?: string;
    weatherSnow?: string;
    weatherMist?: string;
    weatherSmoke?: string;
    weatherHaze?: string;
    weatherDust?: string;
    weatherFog?: string;
    weatherSand?: string;
    weatherAsh?: string;
    weatherSquall?: string;
    weatherTornado?: string;

    // ML Insights Details
    backend: string;
    accuracy: string;
    confidence: string;
    aqiForecast: string;
    next1Hr: string;
    next6Hrs: string;
    next24Hrs: string;
    pollutionSources: string;
    primary: string;
    ensembleVersion: string;
    active: string;
    healthRiskTitle: string;
    riskLow: string;
    riskModerate: string;
    riskHigh: string;
    riskVeryHigh: string;
    riskHazardous: string;
    safe: string;
    notSafe: string;
    outdoor: string;

    // Forecast Details
    high: string;
    low: string;
    aqiImpact: string;
    bestOutdoor: string;
    weatherCorrelation: string;

    // ML Insights Loading & Trends
    initializingMLEngine: string;
    loadingMLModels: string;
    trendImproving: string;
    trendWorsening: string;
    trendStable: string;

    // Weather AQI Impact Labels
    rainClearsPollutants: string;
    windDispersesParticles: string;
    fogTrapsPollutants: string;
    clearSkyOzoneRisk: string;
    stableConditions: string;

    // Best Outdoor Time Labels
    earlyMorning: string;
    morningOrEvening: string;
    middayTime: string;
    anyTimeToday: string;

    // Other
    rain: string;

    // City Names
    cityMumbai: string;
    cityDelhi: string;
    cityBangalore: string;
    cityHyderabad: string;
    cityAhmedabad: string;
    cityChennai: string;
    cityKolkata: string;
    cityPune: string;

    // Detailed Recommendations (Pipe separated)
    rec_excellent_do: string;
    rec_excellent_dont: string;
    rec_moderate_do: string;
    rec_moderate_dont: string;
    rec_sensitive_do: string;
    rec_sensitive_dont: string;
    rec_unhealthy_do: string;
    rec_unhealthy_dont: string;
    rec_hazardous_do: string;
    rec_hazardous_dont: string;
}

// English translations (default)
const en: Translations = {
    appName: 'AirSense Pro',
    realTimeAirQuality: 'Real-time Air Quality',
    gps: 'GPS',
    defaultLocation: 'Default',
    locateMe: 'Locate Me',
    currentLocation: 'Current Location',
    airQualityIndex: 'Air Quality Index',
    good: 'Good',
    moderate: 'Moderate',
    unhealthyForSensitive: 'Unhealthy for Sensitive',
    unhealthy: 'Unhealthy',
    veryUnhealthy: 'Very Unhealthy',
    hazardous: 'Hazardous',
    healthMsgGood: '✨ Great day for outdoor activities!',
    healthMsgModerate: '👍 Air is acceptable. Sensitive people take care.',
    healthMsgSensitive: '⚠️ Limit outdoor activities if you have asthma.',
    healthMsgUnhealthy: '🚫 Everyone should reduce outdoor exposure.',
    healthMsgHazardous: '⛔ Stay indoors! Health emergency conditions.',
    weatherConditions: 'Weather Conditions',
    humidity: 'humidity',
    wind: 'Wind',
    pressure: 'Pressure',
    dry: 'Dry',
    comfort: 'Comfort',
    humid: 'Humid',
    particulateMatter: 'Particulate Matter',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 Excellent air for breathing',
    acceptableAir: '😐 Acceptable for most people',
    wearMask: '😷 Consider wearing a mask outdoors',
    avoidOutdoor: '🚫 Avoid outdoor activities',
    todayForecast: "Today's Forecast",
    fiveDayForecast: '5-Day AQI Forecast',
    settings: 'Settings',
    help: 'Help',
    analysis: 'Analysis',
    history: 'History',
    search: 'Search',
    searchPlaceholder: 'Search city or location...',
    liveData: 'Live',
    apiSources: '7 API Sources',
    updatedNow: 'Updated just now',
    indianCities: 'Major Indian Cities',
    recommendations: 'AI Health Recommendations',
    whatToDo: 'What to Do',
    whatToAvoid: 'What to Avoid',
    mlInsights: 'ML Insights',
    aiPowered: 'AI Powered',
    gasLevels: 'Gas Levels Monitoring',
    selectLanguage: 'Select Language',

    // Cities
    cityLucknow: 'Lucknow',
    cityNagpur: 'Nagpur',
    cityKanpur: 'Kanpur',
    cityJaipur: 'Jaipur',

    // Weather
    weatherClear: 'Clear sky',
    weatherClouds: 'Clouds',
    weatherRain: 'Rain',
    weatherDrizzle: 'Drizzle',
    weatherThunderstorm: 'Thunderstorm',
    weatherSnow: 'Snow',
    weatherMist: 'Mist',
    weatherSmoke: 'Smoke',
    weatherHaze: 'Haze',
    weatherDust: 'Dust',
    weatherFog: 'Fog',
    weatherSand: 'Sand',
    weatherAsh: 'Ash',
    weatherSquall: 'Squall',
    weatherTornado: 'Tornado',
    backend: 'Backend',
    accuracy: 'Accuracy',
    confidence: 'Confidence',
    aqiForecast: 'AQI Forecast',
    next1Hr: '+1 Hour',
    next6Hrs: '+6 Hours',
    next24Hrs: '+24 Hours',
    pollutionSources: 'Pollution Sources (EPA PMF)',
    primary: 'Primary',
    ensembleVersion: 'Ensemble ML',
    active: 'Active',
    healthRiskTitle: 'Health Risk Assessment',
    riskLow: 'LOW',
    riskModerate: 'MODERATE',
    riskHigh: 'HIGH',
    riskVeryHigh: 'VERY HIGH',
    riskHazardous: 'HAZARDOUS',
    safe: 'Safe',
    notSafe: 'Not Recommended',
    outdoor: 'Outdoor',
    high: 'High',
    low: 'Low',
    aqiImpact: 'AQI Impact',
    bestOutdoor: 'Best Outdoor',
    weatherCorrelation: 'Weather-AQI correlation by ML',
    cityMumbai: 'Mumbai',
    cityDelhi: 'Delhi',
    cityBangalore: 'Bangalore',
    cityHyderabad: 'Hyderabad',
    cityAhmedabad: 'Ahmedabad',
    cityChennai: 'Chennai',
    cityKolkata: 'Kolkata',
    cityPune: 'Pune',
    rec_excellent_do: "Perfect day for outdoor activities and sports!|Open windows to ventilate your home.|Great time for running, cycling, or hiking.|Enjoy picnics and outdoor gatherings.",
    rec_excellent_dont: "No restrictions - enjoy the fresh air!",
    rec_moderate_do: "General public can enjoy outdoor activities.|Sensitive individuals should monitor symptoms.|Best to exercise in the morning or evening.|Keep indoor air purifiers running.",
    rec_moderate_dont: "Sensitive groups: limit prolonged outdoor exertion.|Avoid exercising near heavy traffic areas.",
    rec_sensitive_do: "Wear a mask if you have asthma or allergies.|Run air purifiers indoors on medium setting.|Reduce outdoor exercise intensity by 50%.|Keep medication handy if you have respiratory issues.",
    rec_sensitive_dont: "Avoid outdoor jogging if you feel breathless.|Don't keep windows open for long periods.|Children and elderly should limit outdoor time.",
    rec_unhealthy_do: "Wear an N95/KN95 mask when going outside.|Keep all windows and doors closed.|Run air purifiers on high setting.|Take breaks if you must be outdoors.",
    rec_unhealthy_dont: "Avoid all strenuous outdoor activities.|Don't burn candles, incense, or use gas stoves.|Don't let children play outside.|Avoid vacuuming (it stirs up dust).",
    rec_hazardous_do: "STAY INDOORS - health emergency conditions.|Seal window and door gaps with wet towels.|Run multiple air purifiers if available.|Seek immediate medical help for breathing issues.",
    rec_hazardous_dont: "DO NOT go outside unless absolutely necessary.|Don't exercise at all, even indoors.|Don't open any windows or doors.|Don't use exhaust fans that bring in outside air.",
    // New ML & UI Keys
    initializingMLEngine: 'Initializing ML Engine',
    loadingMLModels: 'Loading XGBoost + Random Forest Ensemble...',
    trendImproving: 'Improving',
    trendWorsening: 'Worsening',
    trendStable: 'Stable',
    rainClearsPollutants: 'Rain clears pollutants',
    windDispersesParticles: 'Wind disperses particles',
    fogTrapsPollutants: 'Fog traps pollutants',
    clearSkyOzoneRisk: 'Clear sky = ozone risk',
    stableConditions: 'Stable conditions',
    earlyMorning: 'Early morning (6-8 AM)',
    morningOrEvening: 'Morning or evening',
    middayTime: 'Midday (11 AM - 3 PM)',
    anyTimeToday: 'Any time today',
    rain: 'Rain',
};

// Hindi translations
const hi: Translations = {
    appName: 'एयरसेंस प्रो',
    realTimeAirQuality: 'रीयल-टाइम वायु गुणवत्ता',
    gps: 'जीपीएस',
    defaultLocation: 'डिफ़ॉल्ट',
    locateMe: 'मुझे खोजें',
    currentLocation: 'वर्तमान स्थान',
    airQualityIndex: 'वायु गुणवत्ता सूचकांक',
    good: 'अच्छा',
    moderate: 'मध्यम',
    unhealthyForSensitive: 'संवेदनशील के लिए अस्वस्थ',
    unhealthy: 'अस्वस्थ',
    veryUnhealthy: 'बहुत अस्वस्थ',
    hazardous: 'खतरनाक',
    healthMsgGood: '✨ बाहरी गतिविधियों के लिए बढ़िया दिन!',
    healthMsgModerate: '👍 हवा स्वीकार्य है। संवेदनशील लोग सावधान रहें।',
    healthMsgSensitive: '⚠️ अस्थमा हो तो बाहरी गतिविधियां सीमित करें।',
    healthMsgUnhealthy: '🚫 सभी को बाहर का exposure कम करना चाहिए।',
    healthMsgHazardous: '⛔ घर के अंदर रहें! स्वास्थ्य आपातकाल।',
    weatherConditions: 'मौसम की स्थिति',
    humidity: 'नमी',
    wind: 'हवा',
    pressure: 'दबाव',
    dry: 'सूखा',
    comfort: 'आरामदायक',
    humid: 'नम',
    particulateMatter: 'पार्टिकुलेट मैटर',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 सांस लेने के लिए उत्कृष्ट हवा',
    acceptableAir: '😐 ज्यादातर लोगों के लिए स्वीकार्य',
    wearMask: '😷 बाहर मास्क पहनने पर विचार करें',
    avoidOutdoor: '🚫 बाहरी गतिविधियों से बचें',
    todayForecast: 'आज का पूर्वानुमान',
    fiveDayForecast: '5-दिन AQI पूर्वानुमान',
    settings: 'सेटिंग्स',
    help: 'मदद',
    analysis: 'विश्लेषण',
    history: 'इतिहास',
    search: 'खोजें',
    searchPlaceholder: 'शहर या स्थान खोजें...',
    liveData: 'लाइव',
    apiSources: '7 API स्रोत',
    updatedNow: 'अभी अपडेट हुआ',
    indianCities: 'प्रमुख भारतीय शहर',
    recommendations: 'AI स्वास्थ्य सुझाव',
    whatToDo: 'क्या करें',
    whatToAvoid: 'क्या न करें',
    mlInsights: 'ML अंतर्दृष्टि',
    aiPowered: 'AI संचालित',
    gasLevels: 'गैस स्तर निगरानी',
    selectLanguage: 'भाषा चुनें',
    backend: 'बैकएंड',
    accuracy: 'सटीकता',
    confidence: 'आत्मविश्वास',
    aqiForecast: 'AQI पूर्वानुमान',
    next1Hr: '+1 घंटा',
    next6Hrs: '+6 घंटे',
    next24Hrs: '+24 घंटे',
    pollutionSources: 'प्रदूषण के स्रोत (EPA PMF)',
    primary: 'प्राथमिक',
    ensembleVersion: 'ML संस्करण',
    active: 'सक्रिय',
    healthRiskTitle: 'स्वास्थ्य जोखिम आकलन',
    riskLow: 'कम',
    riskModerate: 'मध्यम',
    riskHigh: 'उच्च',
    riskVeryHigh: 'बहुत उच्च',
    riskHazardous: 'खतरनाक',
    safe: 'सुरक्षित',
    notSafe: 'सिफारिश नहीं',
    outdoor: 'बाहरी',
    high: 'उच्च',
    low: 'निम्न',
    aqiImpact: 'AQI प्रभाव',
    bestOutdoor: 'सर्वोत्तम समय',
    weatherCorrelation: 'ML द्वारा मौसम-AQI संबंध',
    cityMumbai: 'मुंबई',
    cityDelhi: 'दिल्ली',
    cityBangalore: 'बेंगलुरु',
    cityHyderabad: 'हैदराबाद',
    cityAhmedabad: 'अहमदाबाद',
    cityChennai: 'चेन्नई',
    cityKolkata: 'कोलकाता',
    cityPune: 'पुणे',
    cityLucknow: 'लखनऊ',
    cityNagpur: 'नागपुर',
    cityKanpur: 'कानपुर',
    cityJaipur: 'जयपुर',
    weatherClear: 'साफ आकाश',
    weatherClouds: 'बादल',
    weatherRain: 'बारिश',
    weatherDrizzle: 'बूंदाबांदी',
    weatherThunderstorm: 'आंधी',
    weatherSnow: 'बर्फ',
    weatherMist: 'धुंध',
    weatherSmoke: 'धुआं',
    weatherHaze: 'कोहरा',
    weatherDust: 'धूल',
    weatherFog: 'घना कोहरा',
    weatherSand: 'रेत',
    weatherAsh: 'राख',
    weatherSquall: 'तूफान',
    weatherTornado: 'बवंडर',
    rec_excellent_do: "बाहरी गतिविधियों और खेलों के लिए सही दिन!|घर को हवादार बनाने के लिए खिड़कियां खोलें।|दौड़ने, साइकिल चलाने या हाइकिंग के लिए बढ़िया समय।|पिकनिक और बाहरी समारोहों का आनंद लें।",
    rec_excellent_dont: "कोई प्रतिबंध नहीं - ताजी हवा का आनंद लें!",
    rec_moderate_do: "आम जनता बाहरी गतिविधियों का आनंद ले सकती है।|संवेदनशील व्यक्तियों को लक्षणों की निगरानी करनी चाहिए।|सुबह या शाम को व्यायाम करना सबसे अच्छा है।|घर के अंदर एयर प्यूरीफायर चलाते रहें।",
    rec_moderate_dont: "संवेदनशील समूह: लंबे समय तक बाहरी परिश्रम सीमित करें।|भारी यातायात वाले क्षेत्रों के पास व्यायाम करने से बचें।",
    rec_sensitive_do: "यदि आपको अस्थमा या एलर्जी है तो मास्क पहनें।|घर के अंदर मध्यम सेटिंग पर एयर प्यूरीफायर चलाएं।|बाहरी व्यायाम की तीव्रता 50% कम करें।|यदि आपको श्वसन संबंधी समस्याएं हैं तो दवा पास रखें।",
    rec_sensitive_dont: "यदि आपको सांस लेने में तकलीफ हो तो बाहर जॉगिंग न करें।|लंबे समय तक खिड़कियां खुली न रखें।|बच्चों और बुजुर्गों को बाहर का समय सीमित करना चाहिए।",
    rec_unhealthy_do: "बाहर जाते समय N95/KN95 मास्क पहनें।|सभी खिड़कियां और दरवाजे बंद रखें।|उच्च सेटिंग पर एयर प्यूरीफायर चलाएं।|यदि आपको बाहर रहना ही है तो ब्रेक लें।",
    rec_unhealthy_dont: "सभी ज़ोरदार बाहरी गतिविधियों से बचें।|मोमबत्तियां, अगरबत्ती न जलाएं या गैस स्टोव का उपयोग न करें।|बच्चों को बाहर न खेलने दें।|वैक्यूम न करें (यह धूल उड़ाता है)।",
    rec_hazardous_do: "घर के अंदर रहें - स्वास्थ्य आपातकालीन स्थिति।|गीले तौलिये से खिड़की और दरवाजे के अंतराल को सील करें।|उपलब्ध होने पर कई एयर प्यूरीफायर चलाएं।|सांस लेने की समस्याओं के लिए तत्काल चिकित्सा सहायता लें।",
    rec_hazardous_dont: "जब तक बिल्कुल आवश्यक न हो बाहर न जाएं।|बिल्कुल भी व्यायाम न करें, यहां तक कि घर के अंदर भी नहीं।|कोई भी खिड़की या दरवाजे न खोलें।|एग्जॉस्ट फैन का उपयोग न करें जो बाहर की हवा अंदर लाते हैं।",
    // New ML & UI Keys
    initializingMLEngine: 'ML इंजन शुरू हो रहा है',
    loadingMLModels: 'XGBoost + Random Forest लोड हो रहा है...',
    trendImproving: 'सुधार हो रहा है',
    trendWorsening: 'बिगड़ रहा है',
    trendStable: 'स्थिर',
    rainClearsPollutants: 'बारिश प्रदूषकों को साफ करती है',
    windDispersesParticles: 'हवा कणों को फैलाती है',
    fogTrapsPollutants: 'कोहरा प्रदूषकों को रोकता है',
    clearSkyOzoneRisk: 'साफ आकाश = ओजोन जोखिम',
    stableConditions: 'स्थिर परिस्थितियां',
    earlyMorning: 'सुबह जल्दी (6-8 AM)',
    morningOrEvening: 'सुबह या शाम',
    middayTime: 'दोपहर (11 AM - 3 PM)',
    anyTimeToday: 'आज कभी भी',
    rain: 'बारिश',
};

// Tamil translations
const ta: Translations = {
    appName: 'ஏர்சென்ஸ் புரோ',
    realTimeAirQuality: 'நிகழ்நேர காற்று தரம்',
    gps: 'ஜிபிஎஸ்',
    defaultLocation: 'இயல்புநிலை',
    locateMe: 'என்னைக் கண்டறி',
    currentLocation: 'தற்போதைய இடம்',
    airQualityIndex: 'காற்று தர குறியீடு',
    good: 'நல்லது',
    moderate: 'மிதமான',
    unhealthyForSensitive: 'உணர்திறன் உள்ளவர்களுக்கு ஆரோக்கியமற்றது',
    unhealthy: 'ஆரோக்கியமற்றது',
    veryUnhealthy: 'மிகவும் ஆரோக்கியமற்றது',
    hazardous: 'ஆபத்தான',
    healthMsgGood: '✨ வெளிப்புற செயல்பாடுகளுக்கு சிறந்த நாள்!',
    healthMsgModerate: '👍 காற்று ஏற்றுக்கொள்ளத்தக்கது. உணர்திறன் உள்ளவர்கள் கவனமாக இருங்கள்.',
    healthMsgSensitive: '⚠️ ஆஸ்துமா இருந்தால் வெளிப்புற செயல்பாடுகளை குறைக்கவும்.',
    healthMsgUnhealthy: '🚫 அனைவரும் வெளியில் செல்வதை குறைக்க வேண்டும்.',
    healthMsgHazardous: '⛔ வீட்டில் இருங்கள்! சுகாதார அவசரநிலை.',
    weatherConditions: 'வானிலை நிலைமைகள்',
    humidity: 'ஈரப்பதம்',
    wind: 'காற்று',
    pressure: 'அழுத்தம்',
    dry: 'உலர்ந்த',
    comfort: 'சௌகரியம்',
    humid: 'ஈரமான',
    particulateMatter: 'துகள் பொருள்',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 சுவாசிக்க சிறந்த காற்று',
    acceptableAir: '😐 பெரும்பாலானவர்களுக்கு ஏற்றது',
    wearMask: '😷 வெளியே மாஸ்க் அணியுங்கள்',
    avoidOutdoor: '🚫 வெளிப்புற செயல்பாடுகளை தவிர்க்கவும்',
    todayForecast: 'இன்றைய முன்னறிவிப்பு',
    fiveDayForecast: '5-நாள் AQI முன்னறிவிப்பு',
    settings: 'அமைப்புகள்',
    help: 'உதவி',
    analysis: 'பகுப்பாய்வு',
    history: 'வரலாறு',
    search: 'தேடு',
    searchPlaceholder: 'நகரம் அல்லது இடத்தை தேடுங்கள்...',
    liveData: 'நேரடி',
    apiSources: '7 API மூலங்கள்',
    updatedNow: 'இப்போது புதுப்பிக்கப்பட்டது',
    indianCities: 'முக்கிய இந்திய நகரங்கள்',
    recommendations: 'AI சுகாதார பரிந்துரைகள்',
    whatToDo: 'என்ன செய்வது',
    whatToAvoid: 'எதை தவிர்க்க வேண்டும்',
    mlInsights: 'ML நுண்ணறிவு',
    aiPowered: 'AI இயக்கப்படுகிறது',
    gasLevels: 'வாயு நிலை கண்காணிப்பு',
    selectLanguage: 'மொழியை தேர்ந்தெடுக்கவும்',
    backend: 'பின்தளம்',
    accuracy: 'துல்லியம்',
    confidence: 'நம்பகத்தன்மை',
    aqiForecast: 'AQI முன்னறிவிப்பு',
    next1Hr: '+1 மணி',
    next6Hrs: '+6 மணி',
    next24Hrs: '+24 மணி',
    pollutionSources: 'மாசு ஆதாரங்கள் (EPA PMF)',
    primary: 'முதன்மை',
    ensembleVersion: 'Ensemble ML',
    active: 'செயலில்',
    healthRiskTitle: 'ஆரோக்கிய ஆபத்து மதிப்பீடு',
    riskLow: 'குறைவு',
    riskModerate: 'மிதமான',
    riskHigh: 'அதிகம்',
    riskVeryHigh: 'மிக அதிகம்',
    riskHazardous: 'ஆபத்தான',
    safe: 'பாதுகாப்பான',
    notSafe: 'பரிந்துரைக்கப்படவில்லை',
    outdoor: 'வெளிப்புறம்',
    high: 'அதிகம்',
    low: 'குறைவு',
    aqiImpact: 'AQI தாக்கம்',
    bestOutdoor: 'சிறந்த நேரம்',
    weatherCorrelation: 'ML மூலம் வானிலை-AQI தொடர்பு',
    cityMumbai: 'மும்பை',
    cityDelhi: 'தில்லி',
    cityBangalore: 'பெங்களூரு',
    cityHyderabad: 'ஹைதராபாத்',
    cityAhmedabad: 'அகமதாபாத்',
    cityChennai: 'சென்னை',
    cityKolkata: 'கொல்கத்தா',
    cityPune: 'புனே',
    cityLucknow: 'லக்னோ',
    cityNagpur: 'நாக்பூர்',
    cityKanpur: 'கான்பூர்',
    cityJaipur: 'ஜெய்ப்பூர்',
    weatherClear: 'தெளிவான வானம்',
    weatherClouds: 'மேகமூட்டம்',
    weatherRain: 'மழை',
    weatherDrizzle: 'தூறல்',
    weatherThunderstorm: 'இடியுடன் மழை',
    weatherSnow: 'பனி',
    weatherMist: 'மூடுபனி',
    weatherSmoke: 'புகை',
    weatherHaze: 'மங்கல்',
    weatherDust: 'தூசி',
    weatherFog: 'அடர் மூடுபனி',
    weatherSand: 'மணல்',
    weatherAsh: 'சாம்பல்',
    weatherSquall: 'புயல்',
    weatherTornado: 'சூறாவளி',
    rec_excellent_do: "வெளிப்புற செயல்பாடுகளுக்கு சிறந்த நாள்!|காற்றோட்டத்திற்கு ஜன்னல்களை திறக்கவும்.|ஓட்டம், சைக்கிளிங்குக்கு சரியான நேரம்.|வெளியரங்க கூட்டங்களை அனுபவிக்கவும்.",
    rec_excellent_dont: "எந்த தடையும் இல்லை - புதிய காற்றை அனுபவிக்கவும்!",
    rec_moderate_do: "பொது மக்கள் வெளிப்புற செயல்பாடுகளை அனுபவிக்கலாம்.|உணர்திறன் உள்ளவர்கள் அறிகுறிகளைக் கண்காணிக்கவும்.|காலை அல்லது மாலை உடற்பயிற்சி செய்வது சிறந்தது.|உள்ளரங்க காற்று சுத்திகரிப்பான்களைப் பயன்படுத்தவும்.",
    rec_moderate_dont: "உணர்திறன் குழுக்கள்: நீண்ட வெளிப்புற செயல்பாட்டைக் குறைக்கவும்.|நெரிசலான போக்குவரத்து பகுதிகளில் உடற்பயிற்சி தவிர்க்கவும்.",
    rec_sensitive_do: "ஆஸ்துமா/அலர்ஜி இருந்தால் முகக்கவசம் அணியுங்கள்.|காற்று சுத்திகரிப்பான்களை நடுத்தர அமைப்பில் இயக்கவும்.|வெளிப்புற உடற்பயிற்சியை 50% குறைக்கவும்.|சுவாச பிரச்சனை இருந்தால் மருந்துகளை கையில் வைக்கவும்.",
    rec_sensitive_dont: "மூச்சுத் திணறல் இருந்தால் வெளியே ஓடாதீர்கள்.|ஜன்னல்களை நீண்ட நேரம் திறந்து வைக்காதீர்கள்.|குழந்தைகள், முதியவர்கள் வெளிப்புற நேரத்தைக் குறைக்கவும்.",
    rec_unhealthy_do: "வெளியே செல்லும்போது N95/KN95 முகக்கவசம் அணியுங்கள்.|அனைத்து ஜன்னல்கள், கதவுகளை மூடி வைக்கவும்.|காற்று சுத்திகரிப்பான்களை உயர் அமைப்பில் இயக்கவும்.|வெளியே இருக்க வேண்டியிருந்தால் இடைவெளி எடுங்கள்.",
    rec_unhealthy_dont: "கடினமான வெளிப்புற செயல்பாடுகளைத் தவிர்க்கவும்.|மெழுகுவர்த்திகள், ஊதுபத்தி எரிக்காதீர்கள்.|குழந்தைகளை வெளியே விளையாட விடாதீர்கள்.|வேக்யூம் செய்யாதீர்கள் (தூசி கிளம்பும்).",
    rec_hazardous_do: "வீட்டுக்குள்ளேயே இருங்கள் - சுகாதார அவசரநிலை.|ஈரமான துண்டுகளால் ஜன்னல்/கதவு இடைவெளிகளை அடைக்கவும்.|கிடைத்தால் பல காற்று சுத்திகரிப்பான்களை இயக்கவும்.|சுவாச பிரச்சனைகளுக்கு உடனடி மருத்துவ உதவி பெறுங்கள்.",
    rec_hazardous_dont: "மிகவும் அவசியமின்றி வெளியே செல்லாதீர்கள்.|உள்ளரங்கத்திலும் உடற்பயிற்சி செய்யாதீர்கள்.|எந்த ஜன்னலையும் கதவையும் திறக்காதீர்கள்.|வெளிக்காற்றைக் கொண்டுவரும் எக்ஸாஸ்ட் ஃபேன் பயன்படுத்தாதீர்கள்.",
    // New ML & UI Keys
    initializingMLEngine: 'ML இயந்திரம் துவங்குகிறது',
    loadingMLModels: 'XGBoost + Random Forest ஏற்றப்படுகிறது...',
    trendImproving: 'மேம்படுகிறது',
    trendWorsening: 'மோசமாகிறது',
    trendStable: 'நிலையான',
    rainClearsPollutants: 'மழை மாசுகளை நீக்குகிறது',
    windDispersesParticles: 'காற்று துகள்களை சிதறடிக்கிறது',
    fogTrapsPollutants: 'மூடுபனி மாசுகளை சிக்க வைக்கிறது',
    clearSkyOzoneRisk: 'தெளிவான வானம் = ஓசோன் ஆபத்து',
    stableConditions: 'நிலையான சூழல்',
    earlyMorning: 'அதிகாலை (6-8 AM)',
    morningOrEvening: 'காலை அல்லது மாலை',
    middayTime: 'மதியம் (11 AM - 3 PM)',
    anyTimeToday: 'இன்று எந்த நேரமும்',
    rain: 'மழை',
};

// Telugu translations
const te: Translations = {
    appName: 'ఎయిర్‌సెన్స్ ప్రో',
    realTimeAirQuality: 'రియల్-టైమ్ గాలి నాణ్యత',
    gps: 'జిపిఎస్',
    defaultLocation: 'డిఫాల్ట్',
    locateMe: 'నన్ను కనుగొనండి',
    currentLocation: 'ప్రస్తుత స్థానం',
    airQualityIndex: 'గాలి నాణ్యత సూచిక',
    good: 'మంచి',
    moderate: 'మధ్యస్థ',
    unhealthyForSensitive: 'సున్నితమైన వారికి అనారోగ్యం',
    unhealthy: 'అనారోగ్యం',
    veryUnhealthy: 'చాలా అనారోగ్యం',
    hazardous: 'ప్రమాదకరమైన',
    healthMsgGood: '✨ బయటి కార్యకలాపాలకు గొప్ప రోజు!',
    healthMsgModerate: '👍 గాలి ఆమోదయోగ్యం. సున్నితమైన వారు జాగ్రత్త వహించండి.',
    healthMsgSensitive: '⚠️ ఆస్తమా ఉంటే బయటి కార్యకలాపాలు పరిమితం చేయండి.',
    healthMsgUnhealthy: '🚫 అందరూ బయటి ఎక్స్‌పోజర్ తగ్గించాలి.',
    healthMsgHazardous: '⛔ లోపల ఉండండి! ఆరోగ్య అత్యవసర పరిస్థితి.',
    weatherConditions: 'వాతావరణ పరిస్థితులు',
    humidity: 'తేమ',
    wind: 'గాలి',
    pressure: 'పీడనం',
    dry: 'పొడి',
    comfort: 'సౌకర్యం',
    humid: 'తేమగా',
    particulateMatter: 'కణ పదార్థం',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 శ్వాసకు అద్భుతమైన గాలి',
    acceptableAir: '😐 చాలా మందికి ఆమోదయోగ్యం',
    wearMask: '😷 బయట మాస్క్ ధరించడం గురించి ఆలోచించండి',
    avoidOutdoor: '🚫 బయటి కార్యకలాపాలు మానుకోండి',
    todayForecast: 'నేటి అంచనా',
    fiveDayForecast: '5-రోజుల AQI అంచనా',
    settings: 'సెట్టింగ్‌లు',
    help: 'సహాయం',
    analysis: 'విశ్లేషణ',
    history: 'చరిత్ర',
    search: 'వెతకండి',
    searchPlaceholder: 'నగరం లేదా స్థానం వెతకండి...',
    liveData: 'ప్రత్యక్ష',
    apiSources: '7 API మూలాలు',
    updatedNow: 'ఇప్పుడే నవీకరించబడింది',
    indianCities: 'ప్రధాన భారతీయ నగరాలు',
    recommendations: 'AI ఆరోగ్య సిఫార్సులు',
    whatToDo: 'ఏమి చేయాలి',
    whatToAvoid: 'ఏమి మానుకోవాలి',
    mlInsights: 'ML అంతర్దృష్టులు',
    aiPowered: 'AI ఆధారిత',
    gasLevels: 'వాయువు స్థాయి పర్యవేక్షణ',
    selectLanguage: 'భాషను ఎంచుకోండి',
    backend: 'బ్యాకెండ్',
    accuracy: 'ఖచ్చితత్వం',
    confidence: 'విశ్వాసం',
    aqiForecast: 'AQI అంచనా',
    next1Hr: '+1 గంట',
    next6Hrs: '+6 గంటలు',
    next24Hrs: '+24 గంటలు',
    pollutionSources: 'కాలుష్య మూలాలు (EPA PMF)',
    primary: 'ప్రాథమిక',
    ensembleVersion: 'Ensemble ML',
    active: 'క్రియాశీల',
    healthRiskTitle: 'ఆరోగ్య ప్రమాద మూల్యాంకనం',
    riskLow: 'తక్కువ',
    riskModerate: 'మధ్యస్థం',
    riskHigh: 'ఎక్కువ',
    riskVeryHigh: 'చాలా ఎక్కువ',
    riskHazardous: 'ప్రమాదకరం',
    safe: 'సురక్షితం',
    notSafe: 'సిఫారసు చేయబడలేదు',
    outdoor: 'బయట',
    high: 'ఎక్కువ',
    low: 'తక్కువ',
    aqiImpact: 'AQI ప్రభావం',
    bestOutdoor: 'ఉత్తమ సమయం',
    weatherCorrelation: 'ML ద్వారా వాతావరణ-AQI సంబంధం',
    cityMumbai: 'ముంబై',
    cityDelhi: 'ఢిల్లీ',
    cityBangalore: 'బెంగళూరు',
    cityHyderabad: 'హైదరాబాద్',
    cityAhmedabad: 'అహ్మదాబాద్',
    cityChennai: 'చెన్నై',
    cityKolkata: 'కోల్‌కతా',
    cityPune: 'పుణే',
    cityLucknow: 'లక్నో',
    cityNagpur: 'నాగ్‌పూర్',
    cityKanpur: 'కాన్పూర్',
    cityJaipur: 'జైపూర్',
    weatherClear: 'తేటగా ఆకాశం',
    weatherClouds: 'మేఘాలు',
    weatherRain: 'వర్షం',
    weatherDrizzle: 'చిరుజల్లులు',
    weatherThunderstorm: 'ఉరుములతో వర్షం',
    weatherSnow: 'మంచు',
    weatherMist: 'పొగమంచు',
    weatherSmoke: 'పొగ',
    weatherHaze: 'మసకబారిన',
    weatherDust: 'దుమ్ము',
    weatherFog: 'దట్టమైన పొగమంచు',
    weatherSand: 'ఇసుక',
    weatherAsh: 'బూడిద',
    weatherSquall: 'తుఫాను',
    weatherTornado: 'సుడిగాలి',
    rec_excellent_do: "బయటి కార్యకలాపాలకు అద్భుతమైన రోజు!|గాలి కోసం కిటికీలు తెరవండి.|పరుగు, సైక్లింగ్‌కు మంచి సమయం.|పికనిక్‌లు, బయటి సమావేశాలను ఆనందించండి.",
    rec_excellent_dont: "ఎటువంటి పరిమితులు లేవు - తాజా గాలిని ఆనందించండి!",
    rec_moderate_do: "సాధారణ ప్రజలు బయటి కార్యకలాపాలను ఆస్వాదించవచ్చు.|సున్నితమైన వ్యక్తులు లక్షణాలను పర్యవేక్షించాలి.|ఉదయం లేదా సాయంత్రం వ్యాయామం చేయడం మంచిది.|ఇండోర్ ఎయిర్ ప్యూరిఫైయర్లను వాడండి.",
    rec_moderate_dont: "సున్నితమైన సమూహాలు: సుదీర్ఘ బయటి శ్రమను పరిమితం చేయండి.|భారీ ట్రాఫిక్ ప్రాంతాల్లో వ్యాయామం చేయకండి.",
    rec_sensitive_do: "ఆస్తమా/అలెర్జీ ఉంటే మాస్క్ ధరించండి.|ఎయిర్ ప్యూరిఫైయర్లను మధ్యస్థంగా అమర్చండి.|బయటి వ్యాయామ తీవ్రతను 50% తగ్గించండి.|శ్వాసకోశ సమస్యలు ఉంటే మందులు అందుబాటులో ఉంచుకోండి.",
    rec_sensitive_dont: "ఊపిరి తీసుకోవడం కష్టంగా ఉంటే బయట పరుగెత్తకండి.|కిటికీలను ఎక్కువసేపు తెరిచి ఉంచకండి.|పిల్లలు, వృద్ధులు బయట సమయాన్ని తగ్గించాలి.",
    rec_unhealthy_do: "బయటకు వెళ్ళేటప్పుడు N95/KN95 మాస్క్ ధరించండి.|అన్ని కిటికీలు, తలుపులు మూసి ఉంచండి.|ఎయిర్ ప్యూరిఫైయర్లను అధిక సెట్టింగ్‌లో వాడండి.|బయట ఉండవలసి వస్తే విరామాలు తీసుకోండి.",
    rec_unhealthy_dont: "కఠినమైన బయటి కార్యకలాపాలను నివారించండి.|కొవ్వొత్తులు, అగరబత్తులు వెలిగించకండి.|పిల్లలను బయట ఆడనివ్వకండి.|వాక్యూమ్ చేయకండి (దుమ్ము లేస్తుంది).",
    rec_hazardous_do: "లోపలే ఉండండి - ఆరోగ్య అత్యవసర పరిస్థితి.|తడి టవల్స్‌తో కిటికీ/తలుపు ఖాళీలను మూయండి.|అందుబాటులో ఉంటే బహుళ ఎయిర్ ప్యూరిఫైయర్లు వాడండి.|శ్వాస సమస్యలకు వెంటనే వైద్య సహాయం పొందండి.",
    rec_hazardous_dont: "అత్యవసరం కాకపోతే బయటకు వెళ్ళకండి.|ఇండోర్స్‌లో కూడా వ్యాయామం చేయకండి.|ఏ కిటికీలు లేదా తలుపులు తెరవకండి.|బయటి గాలిని తీసుకొచ్చే ఎగ్జాస్ట్ ఫ్యాన్లు వాడకండి.",
    // New ML & UI Keys
    initializingMLEngine: 'ML ఇంజన్ ప్రారంభమవుతోంది',
    loadingMLModels: 'XGBoost + Random Forest లోడ్ అవుతోంది...',
    trendImproving: 'మెరుగవుతోంది',
    trendWorsening: 'క్షీణిస్తోంది',
    trendStable: 'స్థిరంగా ఉంది',
    rainClearsPollutants: 'వర్షం కాలుష్యాన్ని తొలగిస్తుంది',
    windDispersesParticles: 'గాలి కణాలను చెదరగొడుతుంది',
    fogTrapsPollutants: 'పొగమంచు కాలుష్యాన్ని బంధిస్తుంది',
    clearSkyOzoneRisk: 'స్పష్టమైన ఆకాశం = ఓజోన్ ప్రమాదం',
    stableConditions: 'స్థిర పరిస్థితులు',
    earlyMorning: 'తెల్లవారుజాము (6-8 AM)',
    morningOrEvening: 'ఉదయం లేదా సాయంత్రం',
    middayTime: 'మధ్యాహ్నం (11 AM - 3 PM)',
    anyTimeToday: 'ఇవాళ ఎప్పుడైనా',
    rain: 'వర్షం',
};

// Bengali translations
const bn: Translations = {
    appName: 'এয়ারসেন্স প্রো',
    realTimeAirQuality: 'রিয়েল-টাইম বায়ু মান',
    gps: 'জিপিএস',
    defaultLocation: 'ডিফল্ট',
    locateMe: 'আমাকে খুঁজুন',
    currentLocation: 'বর্তমান অবস্থান',
    airQualityIndex: 'বায়ু মান সূচক',
    good: 'ভাল',
    moderate: 'মাঝারি',
    unhealthyForSensitive: 'সংবেদনশীলদের জন্য অস্বাস্থ্যকর',
    unhealthy: 'অস্বাস্থ্যকর',
    veryUnhealthy: 'খুব অস্বাস্থ্যকর',
    hazardous: 'বিপজ্জনক',
    healthMsgGood: '✨ বাইরের ক্রিয়াকলাপের জন্য দুর্দান্ত দিন!',
    healthMsgModerate: '👍 বাতাস গ্রহণযোগ্য। সংবেদনশীল ব্যক্তিরা যত্ন নিন।',
    healthMsgSensitive: '⚠️ হাঁপানি থাকলে বাইরের কার্যকলাপ সীমিত করুন।',
    healthMsgUnhealthy: '🚫 সবাইকে বাইরের এক্সপোজার কমাতে হবে।',
    healthMsgHazardous: '⛔ ভিতরে থাকুন! স্বাস্থ্য জরুরি অবস্থা।',
    weatherConditions: 'আবহাওয়ার অবস্থা',
    humidity: 'আর্দ্রতা',
    wind: 'বাতাস',
    pressure: 'চাপ',
    dry: 'শুষ্ক',
    comfort: 'আরামদায়ক',
    humid: 'আর্দ্র',
    particulateMatter: 'কণা পদার্থ',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 শ্বাস নেওয়ার জন্য চমৎকার বায়ু',
    acceptableAir: '😐 বেশিরভাগ মানুষের জন্য গ্রহণযোগ্য',
    wearMask: '😷 বাইরে মাস্ক পরার কথা বিবেচনা করুন',
    avoidOutdoor: '🚫 বাইরের কার্যকলাপ এড়িয়ে চলুন',
    todayForecast: 'আজকের পূর্বাভাস',
    fiveDayForecast: '৫-দিনের AQI পূর্বাভাস',
    settings: 'সেটিংস',
    help: 'সাহায্য',
    analysis: 'বিশ্লেষণ',
    history: 'ইতিহাস',
    search: 'খুঁজুন',
    searchPlaceholder: 'শহর বা অবস্থান খুঁজুন...',
    liveData: 'সরাসরি',
    apiSources: '৭ API উৎস',
    updatedNow: 'এইমাত্র আপডেট হয়েছে',
    indianCities: 'প্রধান ভারতীয় শহর',
    recommendations: 'AI স্বাস্থ্য সুপারিশ',
    whatToDo: 'কী করবেন',
    whatToAvoid: 'কী এড়াবেন',
    mlInsights: 'ML অন্তর্দৃষ্টি',
    aiPowered: 'AI চালিত',
    gasLevels: 'গ্যাস স্তর পর্যবেক্ষণ',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    backend: 'ব্যাকএন্ড',
    accuracy: 'নির্ভুলতা',
    confidence: 'বিশ্বাস',
    aqiForecast: 'AQI পূর্বাভাস',
    next1Hr: '+১ ঘণ্টা',
    next6Hrs: '+৬ ঘণ্টা',
    next24Hrs: '+২৪ ঘণ্টা',
    pollutionSources: 'দূষণের উৎস (EPA PMF)',
    primary: 'প্রাথমিক',
    ensembleVersion: 'Ensemble ML',
    active: 'সক্রিয়',
    healthRiskTitle: 'স্বাস্থ্য ঝুঁকি মূল্যায়ন',
    riskLow: 'কম',
    riskModerate: 'মাঝারি',
    riskHigh: 'বেশি',
    riskVeryHigh: 'অনেক বেশি',
    riskHazardous: 'বিপজ্জনক',
    safe: 'নিরাপদ',
    notSafe: 'সুপারিশ নয়',
    outdoor: 'বাইরে',
    high: 'বেশি',
    low: 'কম',
    aqiImpact: 'AQI প্রভাব',
    bestOutdoor: 'সেরা সময়',
    weatherCorrelation: 'ML দ্বারা আবহাওয়া-AQI সম্পর্ক',
    cityMumbai: 'মুম্বাই',
    cityDelhi: 'দিল্লি',
    cityBangalore: 'বেঙ্গালুরু',
    cityHyderabad: 'হায়দরাবাদ',
    cityAhmedabad: 'আহমেদাবাদ',
    cityChennai: 'চেন্নাই',
    cityKolkata: 'কলকাতা',
    cityPune: 'পুনে',
    cityLucknow: 'লখনউ',
    cityNagpur: 'নাগপুর',
    cityKanpur: 'কানপুর',
    cityJaipur: 'জয়পুর',
    weatherClear: 'পরিষ্কার আকাশ',
    weatherClouds: 'মেঘলা',
    weatherRain: 'বৃষ্টি',
    weatherDrizzle: 'গুঁড়ি গুঁড়ি বৃষ্টি',
    weatherThunderstorm: 'বজ্রঝড়',
    weatherSnow: 'তুষার',
    weatherMist: 'কুয়াশা',
    weatherSmoke: 'ধোঁয়া',
    weatherHaze: 'ধোঁয়াশা',
    weatherDust: 'ধুলো',
    weatherFog: 'ঘন কুয়াশা',
    weatherSand: 'বালি',
    weatherAsh: 'ছাই',
    weatherSquall: 'ঝড়',
    weatherTornado: 'টর্নেডো',
    rec_excellent_do: "বাইরের কার্যকলাপের জন্য দুর্দান্ত দিন!|বাতাস চলাচলের জন্য জানালা খুলুন।|দৌড়, সাইকেল চালানোর জন্য ভালো সময়।|পিকনিক এবং বাইরের সমাবেশ উপভোগ করুন।",
    rec_excellent_dont: "কোনো বিধিনিষেধ নেই - তাজা বাতাস উপভোগ করুন!",
    rec_moderate_do: "সাধারণ মানুষ বাইরের কার্যকলাপ উপভোগ করতে পারেন।|সংবেদনশীল ব্যক্তিদের লক্ষণ পর্যবেক্ষণ করা উচিত।|সকাল বা সন্ধ্যায় ব্যায়াম করা ভালো।|ইনডোর এয়ার পিউরিফায়ার ব্যবহার করুন।",
    rec_moderate_dont: "সংবেদনশীল গোষ্ঠী: দীর্ঘ বাইরের পরিশ্রম সীমিত করুন।|ভারী ট্রাফিক এলাকায় ব্যায়াম এড়িয়ে চলুন।",
    rec_sensitive_do: "হাঁপানি/অ্যালার্জি থাকলে মাস্ক পরুন।|এয়ার পিউরিফায়ার মাঝারি সেটিংয়ে চালান।|বাইরের ব্যায়ামের তীব্রতা ৫০% কমান।|শ্বাসকষ্ট থাকলে ওষুধ হাতের কাছে রাখুন।",
    rec_sensitive_dont: "শ্বাসকষ্ট থাকলে বাইরে দৌড়াবেন না।|জানালা দীর্ঘ সময় খোলা রাখবেন না।|শিশু ও বৃদ্ধদের বাইরের সময় সীমিত করুন।",
    rec_unhealthy_do: "বাইরে যাওয়ার সময় N95/KN95 মাস্ক পরুন।|সব জানালা ও দরজা বন্ধ রাখুন।|এয়ার পিউরিফায়ার উচ্চ সেটিংয়ে চালান।|বাইরে থাকতে হলে বিশ্রাম নিন।",
    rec_unhealthy_dont: "কঠিন বাইরের কার্যকলাপ এড়িয়ে চলুন।|মোমবাতি, ধূপ জ্বালাবেন না।|শিশুদের বাইরে খেলতে দেবেন না।|ভ্যাকুয়াম করবেন না (ধুলো ওঠে)।",
    rec_hazardous_do: "বাড়িতে থাকুন - স্বাস্থ্য জরুরি অবস্থা।|ভেজা তোয়ালে দিয়ে জানালা/দরজার ফাঁক বন্ধ করুন।|সম্ভব হলে একাধিক এয়ার পিউরিফায়ার চালান।|শ্বাসকষ্টের জন্য অবিলম্বে চিকিৎসা সাহায্য নিন।",
    rec_hazardous_dont: "অত্যন্ত প্রয়োজন ছাড়া বাইরে যাবেন না।|ইনডোরেও ব্যায়াম করবেন না।|কোনো জানালা বা দরজা খুলবেন না।|বাইরের বাতাস আনা এক্সহস্ট ফ্যান ব্যবহার করবেন না।",
    // New ML & UI Keys
    initializingMLEngine: 'ML ইঞ্জিন শুরু হচ্ছে',
    loadingMLModels: 'XGBoost + Random Forest লোড হচ্ছে...',
    trendImproving: 'উন্নতি হচ্ছে',
    trendWorsening: 'খারাপ হচ্ছে',
    trendStable: 'স্থিতিশীল',
    rainClearsPollutants: 'বৃষ্টি দূষণ দূর করে',
    windDispersesParticles: 'বাতাস কণা ছড়িয়ে দেয়',
    fogTrapsPollutants: 'কুয়াশা দূষণ আটকায়',
    clearSkyOzoneRisk: 'পরিষ্কার আকাশ = ওজোন ঝুঁকি',
    stableConditions: 'স্থিতিশীল অবস্থা',
    earlyMorning: 'সকালে তাড়াতাড়ি (৬-৮ AM)',
    morningOrEvening: 'সকাল বা সন্ধ্যা',
    middayTime: 'দুপুর (১১ AM - ৩ PM)',
    anyTimeToday: 'আজ যেকোনো সময়',
    rain: 'বৃষ্টি',
};

// Marathi translations
const mr: Translations = {
    appName: 'एयरसेन्स प्रो',
    realTimeAirQuality: 'रियल-टाइम हवा गुणवत्ता',
    gps: 'जीपीएस',
    defaultLocation: 'डीफॉल्ट',
    locateMe: 'मला शोधा',
    currentLocation: 'सध्याचे स्थान',
    airQualityIndex: 'हवा गुणवत्ता निर्देशांक',
    good: 'चांगले',
    moderate: 'मध्यम',
    unhealthyForSensitive: 'संवेदनशीलांसाठी अस्वास्थ्यकर',
    unhealthy: 'अस्वास्थ्यकर',
    veryUnhealthy: 'खूप अस्वास्थ्यकर',
    hazardous: 'धोकादायक',
    healthMsgGood: '✨ बाहेरच्या क्रियाकलापांसाठी उत्तम दिवस!',
    healthMsgModerate: '👍 हवा स्वीकार्य आहे. संवेदनशील लोकांनी काळजी घ्या.',
    healthMsgSensitive: '⚠️ दमा असल्यास बाहेरच्या क्रियाकलाप मर्यादित करा.',
    healthMsgUnhealthy: '🚫 सगळ्यांनी बाहेरचा संपर्क कमी करावा.',
    healthMsgHazardous: '⛔ आत रहा! आरोग्य आणीबाणी.',
    weatherConditions: 'हवामान स्थिती',
    humidity: 'आर्द्रता',
    wind: 'वारा',
    pressure: 'दाब',
    dry: 'कोरडे',
    comfort: 'आरामदायक',
    humid: 'दमट',
    particulateMatter: 'कण पदार्थ',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 श्वासोच्छवासासाठी उत्कृष्ट हवा',
    acceptableAir: '😐 बहुतेक लोकांसाठी स्वीकार्य',
    wearMask: '😷 बाहेर मास्क घालणे विचारात घ्या',
    avoidOutdoor: '🚫 बाहेरच्या क्रियाकलाप टाळा',
    todayForecast: 'आजचा अंदाज',
    fiveDayForecast: '५-दिवसांचा AQI अंदाज',
    settings: 'सेटिंग्ज',
    help: 'मदत',
    analysis: 'विश्लेषण',
    history: 'इतिहास',
    search: 'शोधा',
    searchPlaceholder: 'शहर किंवा स्थान शोधा...',
    liveData: 'थेट',
    apiSources: '७ API स्रोत',
    updatedNow: 'आत्ताच अपडेट',
    indianCities: 'प्रमुख भारतीय शहरे',
    recommendations: 'AI आरोग्य शिफारस',
    whatToDo: 'काय करावे',
    whatToAvoid: 'काय टाळावे',
    mlInsights: 'ML अंतर्दृष्टी',
    aiPowered: 'AI चालित',
    gasLevels: 'गॅस पातळी देखरेख',
    selectLanguage: 'भाषा निवडा',
    backend: 'बॅकएंड',
    accuracy: 'अचूकता',
    confidence: 'विश्वास',
    aqiForecast: 'AQI अंदाज',
    next1Hr: '+१ तास',
    next6Hrs: '+६ तास',
    next24Hrs: '+२४ तास',
    pollutionSources: 'प्रदूषण स्रोत (EPA PMF)',
    primary: 'प्राथमिक',
    ensembleVersion: 'Ensemble ML',
    active: 'सक्रिय',
    healthRiskTitle: 'आरोग्य जोखीम मूल्यांकन',
    riskLow: 'कमी',
    riskModerate: 'मध्यम',
    riskHigh: 'जास्त',
    riskVeryHigh: 'खूप जास्त',
    riskHazardous: 'धोकादायक',
    safe: 'सुरक्षित',
    notSafe: 'शिफारस नाही',
    outdoor: 'बाहेर',
    high: 'जास्त',
    low: 'कमी',
    aqiImpact: 'AQI प्रभाव',
    bestOutdoor: 'सर्वोत्तम वेळ',
    weatherCorrelation: 'ML द्वारे हवामान-AQI संबंध',
    cityMumbai: 'मुंबई',
    cityDelhi: 'दिल्ली',
    cityBangalore: 'बेंगळुरू',
    cityHyderabad: 'हैदराबाद',
    cityAhmedabad: 'अहमदाबाद',
    cityChennai: 'चेन्नई',
    cityKolkata: 'कोलकाता',
    cityPune: 'पुणे',
    cityLucknow: 'लखनौ',
    cityNagpur: 'नागपूर',
    cityKanpur: 'कानपूर',
    cityJaipur: 'जयपूर',
    weatherClear: 'स्वच्छ आकाश',
    weatherClouds: 'ढगाळ',
    weatherRain: 'पाऊस',
    weatherDrizzle: 'रिमझिम पाऊस',
    weatherThunderstorm: 'गडगडाटी वादळ',
    weatherSnow: 'बर्फ',
    weatherMist: 'धुके',
    weatherSmoke: 'धूर',
    weatherHaze: 'धूसर',
    weatherDust: 'धूळ',
    weatherFog: 'दाट धुके',
    weatherSand: 'वाळू',
    weatherAsh: 'राख',
    weatherSquall: 'वादळ',
    weatherTornado: 'चक्रीवादळ',
    rec_excellent_do: "बाहेरच्या क्रियाकलापांसाठी उत्तम दिवस!|घर हवेशीर करण्यासाठी खिडक्या उघडा.|धावणे, सायकलिंगसाठी चांगला वेळ.|पिकनिक आणि बाहेरच्या मेळाव्यांचा आनंद घ्या.",
    rec_excellent_dont: "कोणतेही निर्बंध नाहीत - ताज्या हवेचा आनंद घ्या!",
    rec_moderate_do: "सामान्य लोक बाहेरच्या क्रियाकलापांचा आनंद घेऊ शकतात.|संवेदनशील व्यक्तींनी लक्षणे पहावीत.|सकाळी किंवा संध्याकाळी व्यायाम करणे सर्वोत्तम.|इनडोअर एअर प्युरिफायर वापरा.",
    rec_moderate_dont: "संवेदनशील गट: दीर्घ बाहेरचे श्रम मर्यादित करा.|जड वाहतूक क्षेत्रात व्यायाम टाळा.",
    rec_sensitive_do: "दमा/ॲलर्जी असल्यास मास्क घाला.|एअर प्युरिफायर मध्यम सेटिंगवर चालवा.|बाहेरच्या व्यायामाची तीव्रता ५०% कमी करा.|श्वसन समस्या असल्यास औषधे हातात ठेवा.",
    rec_sensitive_dont: "श्वास घेण्यास त्रास होत असल्यास बाहेर धावू नका.|खिडक्या जास्त वेळ उघड्या ठेवू नका.|मुले आणि वृद्धांनी बाहेरचा वेळ कमी करावा.",
    rec_unhealthy_do: "बाहेर जाताना N95/KN95 मास्क घाला.|सर्व खिडक्या आणि दारे बंद ठेवा.|एअर प्युरिफायर उच्च सेटिंगवर चालवा.|बाहेर राहणे आवश्यक असल्यास विश्रांती घ्या.",
    rec_unhealthy_dont: "कठीण बाहेरच्या क्रियाकलाप टाळा.|मेणबत्त्या, अगरबत्ती पेटवू नका.|मुलांना बाहेर खेळू देऊ नका.|व्हॅक्यूम करू नका (धूळ उडते).",
    rec_hazardous_do: "आत रहा - आरोग्य आणीबाणी.|ओल्या टॉवेलने खिडकी/दरवाजाच्या फटी बंद करा.|शक्य असल्यास अनेक एअर प्युरिफायर चालवा.|श्वासाच्या समस्यांसाठी त्वरित वैद्यकीय मदत घ्या.",
    rec_hazardous_dont: "अत्यंत आवश्यक असल्याशिवाय बाहेर जाऊ नका.|इनडोअरमध्येही व्यायाम करू नका.|कोणतीही खिडकी किंवा दार उघडू नका.|बाहेरची हवा आणणारे एक्झॉस्ट फॅन वापरू नका.",
    // New ML & UI Keys
    initializingMLEngine: 'ML इंजिन सुरू होत आहे',
    loadingMLModels: 'XGBoost + Random Forest लोड होत आहे...',
    trendImproving: 'सुधारत आहे',
    trendWorsening: 'बिघडत आहे',
    trendStable: 'स्थिर',
    rainClearsPollutants: 'पाऊस प्रदूषण साफ करतो',
    windDispersesParticles: 'वारा कण विखुरतो',
    fogTrapsPollutants: 'धुके प्रदूषण अडकवते',
    clearSkyOzoneRisk: 'स्वच्छ आकाश = ओझोन धोका',
    stableConditions: 'स्थिर परिस्थिती',
    earlyMorning: 'सकाळी लवकर (६-८ AM)',
    morningOrEvening: 'सकाळ किंवा संध्याकाळ',
    middayTime: 'दुपार (११ AM - ३ PM)',
    anyTimeToday: 'आज कधीही',
    rain: 'पाऊस',
};

// Kannada translations
const kn: Translations = {
    appName: 'ಏರ್‌ಸೆನ್ಸ್ ಪ್ರೊ',
    realTimeAirQuality: 'ನೈಜ-ಸಮಯ ಗಾಳಿ ಗುಣಮಟ್ಟ',
    gps: 'ಜಿಪಿಎಸ್',
    defaultLocation: 'ಡೀಫಾಲ್ಟ್',
    locateMe: 'ನನ್ನ ಸ್ಥಳ',
    currentLocation: 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
    airQualityIndex: 'ಗಾಳಿ ಗುಣಮಟ್ಟ ಸೂಚ್ಯಂಕ',
    good: 'ಉತ್ತಮ',
    moderate: 'ಮಧ್ಯಮ',
    unhealthyForSensitive: 'ಸೂಕ್ಷ್ಮರಿಗೆ ಅನಾರೋಗ್ಯಕರ',
    unhealthy: 'ಅನಾರೋಗ್ಯಕರ',
    veryUnhealthy: 'ತುಂಬಾ ಅನಾರೋಗ್ಯಕರ',
    hazardous: 'ಅಪಾಯಕಾರಿ',
    healthMsgGood: '✨ ಹೊರಗಿನ ಚಟುವಟಿಕೆಗಳಿಗೆ ಸೂಕ್ತ ದಿನ!',
    healthMsgModerate: '👍 ಗಾಳಿ ಪರವಾಗಿಲ್ಲ. ಸೂಕ್ಷ್ಮ ವ್ಯಕ್ತಿಗಳು ಗಮನವಿರಲಿ.',
    healthMsgSensitive: '⚠️ ಆಸ್ತಮಾ ಇದ್ದರೆ ಹೊರಾಂಗಣ ಚಟುವಟಿಕೆಗಳನ್ನು ಮಿತಿಗೊಳಿಸಿ.',
    healthMsgUnhealthy: '🚫 ಎಲ್ಲರೂ ಹೊರಗಿನ ಸಂಪರ್ಕವನ್ನು ಕಡಿಮೆ ಮಾಡಬೇಕು.',
    healthMsgHazardous: '⛔ ಮನೆಯಲ್ಲೇ ಇರಿ! ಆರೋಗ್ಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿ.',
    weatherConditions: 'ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿಗಳು',
    humidity: 'ಆರ್ದ್ರತೆ',
    wind: 'ಗಾಳಿ',
    pressure: 'ಒತ್ತಡ',
    dry: 'ಶುಷ್ಕ',
    comfort: 'ಆರಾಮದಾಯಕ',
    humid: 'ತೇವಾಂಶ',
    particulateMatter: 'ಕಣ ದ್ರವ್ಯ',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 ಉಸಿರಾಡಲು ಉತ್ತಮವಾದ ಗಾಳಿ',
    acceptableAir: '😐 ಹೆಚ್ಚಿನ ಜನರಿಗೆ ಸ್ವೀಕಾರಾರ್ಹ',
    wearMask: '😷 ಹೊರಗೆ ಮಾಸ್ಕ್ ಧರಿಸಿ',
    avoidOutdoor: '🚫 ಹೊರಾಂಗಣ ಚಟುವಟಿಕೆಗಳನ್ನು ತಪ್ಪಿಸಿ',
    todayForecast: 'ಇಂದಿನ ಮುನ್ಸೂಚನೆ',
    fiveDayForecast: '೫-ದಿನದ AQI ಮುನ್ಸೂಚನೆ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    help: 'ಸಹಾಯ',
    analysis: 'ವಿಶ್ಲೇಷಣೆ',
    history: 'ಇತಿಹಾಸ',
    search: 'ಹುಡುಕಿ',
    searchPlaceholder: 'ನಗರ ಅಥವಾ ಸ್ಥಳವನ್ನು ಹುಡುಕಿ...',
    liveData: 'ನೇರ',
    apiSources: '೭ API ಮೂಲಗಳು',
    updatedNow: 'ಈಗಷ್ಟೇ ನವೀಕರಿಸಲಾಗಿದೆ',
    indianCities: 'ಪ್ರಮುಖ ಭಾರತೀಯ ನಗರಗಳು',
    recommendations: 'AI ಆರೋಗ್ಯ ಸಲಹೆಗಳು',
    whatToDo: 'ಏನು ಮಾಡಬೇಕು',
    whatToAvoid: 'ಏನು ತಪ್ಪಿಸಬೇಕು',
    mlInsights: 'ಯಂತ್ರ ಕಲಿಕೆ ಒಳನೋಟಗಳು',
    aiPowered: 'AI ಚಾಲಿತ',
    gasLevels: 'ಅನಿಲ ಮಟ್ಟಗಳು',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',

    backend: 'ಬ್ಯಾಕೆಂಡ್',
    accuracy: 'ನಿಖರತೆ',
    confidence: 'ವಿಶ್ವಾಸಾರ್ಹತೆ',
    aqiForecast: 'AQI ಮುನ್ಸೂಚನೆ',
    next1Hr: '+೧ ಗಂಟೆ',
    next6Hrs: '+೬ ಗಂಟೆಗಳು',
    next24Hrs: '+೨೪ ಗಂಟೆಗಳು',
    pollutionSources: 'ಮಾಲಿನ್ಯ ಮೂಲಗಳು (EPA PMF)',
    primary: 'ಪ್ರಾಥಮಿಕ',
    ensembleVersion: 'Ensemble ML',
    active: 'ಸಕ್ರಿಯ',
    healthRiskTitle: 'ಆರೋಗ್ಯ ಅಪಾಯದ ಮೌಲ್ಯಮಾಪನ',
    riskLow: 'ಕಡಿಮೆ',
    riskModerate: 'ಮಧ್ಯಮ',
    riskHigh: 'ಹೆಚ್ಚು',
    riskVeryHigh: 'ತುಂಬಾ ಹೆಚ್ಚು',
    riskHazardous: 'ಅಪಾಯಕಾರಿ',
    safe: 'ಸುರಕ್ಷಿತ',
    notSafe: 'ಸುರಕ್ಷಿತವಲ್ಲ',
    outdoor: 'ಹೊರಾಂಗಣ',
    high: 'ಗರಿಷ್ಠ',
    low: 'ಕನಿಷ್ಠ',
    aqiImpact: 'AQI ಪರಿಣಾಮ',
    bestOutdoor: 'ಉತ್ತಮ ಹೊರಾಂಗಣ',
    weatherCorrelation: 'ML ಮೂಲಕ ಹವಾಮಾನ-AQI ಸಂಬಂಧ',

    cityMumbai: 'ಮುಂಬೈ',
    cityDelhi: 'ದೆಹಲಿ',
    cityBangalore: 'ಬೆಂಗಳೂರು',
    cityHyderabad: 'ಹೈದರಾಬಾದ್',
    cityAhmedabad: 'ಅಹಮದಾಬಾದ್',
    cityChennai: 'ಚೆನ್ನೈ',
    cityKolkata: 'ಕೋಲ್ಕತ್ತಾ',
    cityPune: 'ಪುಣೆ',
    cityLucknow: 'ಲಕ್ನೋ',
    cityNagpur: 'ನಾಗ್ಪುರ',
    cityKanpur: 'ಕಾನ್ಪುರ',
    cityJaipur: 'ಜೈಪುರ',

    weatherClear: 'ತಿಳಿ ಆಕಾಶ',
    weatherClouds: 'ಮೋಡ ಕವಿದಿದೆ',
    weatherRain: 'ಮಳೆ',
    weatherDrizzle: 'ತುಂತುರು ಮಳೆ',
    weatherThunderstorm: 'ಗುಡುಗು ಸಹಿತ ಮಳೆ',
    weatherSnow: 'ಹಿಮ',
    weatherMist: 'ಮಂಜು',
    weatherSmoke: 'ಹೊಗೆ',
    weatherHaze: 'ಮಬ್ಬು',
    weatherDust: 'ಧೂಳು',
    weatherFog: 'ದಟ್ಟ ಮಂಜು',
    weatherSand: 'ಮರಳು',
    weatherAsh: 'ಬೂದಿ',
    weatherSquall: 'ಬಿರುಗಾಳಿ',
    weatherTornado: 'ಸುಂಟರಗಾಳಿ',

    rec_excellent_do: "ಹೊರಾಂಗಣ ಚಟುವಟಿಕೆಗಳಿಗೆ ಉತ್ತಮ ದಿನ!|ಕಿಟಕಿಗಳನ್ನು ತೆರೆಯಿರಿ.|ಓಟ, ಸೈಕ್ಲಿಂಗ್‌ಗೆ ಸೂಕ್ತವಾಗಿದೆ.|ಪ್ರವಾಸ ಮತ್ತು ಕೂಟಗಳನ್ನು ಆನಂದಿಸಿ.",
    rec_excellent_dont: "ಯಾವುದೇ ನಿರ್ಬಂಧಗಳಿಲ್ಲ - ತಾಜಾ ಗಾಳಿಯನ್ನು ಆನಂದಿಸಿ!",
    rec_moderate_do: "ಸಾಮಾನ್ಯವಾಗಿ ಹೊರಾಂಗಣ ಚಟುವಟಿಕೆಗಳನ್ನು ಆನಂದಿಸಬಹುದು.|ಸೂಕ್ಷ್ಮ ವ್ಯಕ್ತಿಗಳು ರೋಗಲಕ್ಷಣಗಳನ್ನು ಗಮನಿಸಬೇಕು.|ಬೆಳಿಗ್ಗೆ ಅಥವಾ ಸಂಜೆ ವ್ಯಾಯಾಮ ಮಾಡುವುದು ಉತ್ತಮ.|ಒಳಾಂಗಣ ಏರ್ ಪ್ಯೂರಿಫೈಯರ್‌ಗಳನ್ನು ಬಳಸಿ.",
    rec_moderate_dont: "ಸೂಕ್ಷ್ಮ ಗುಂಪುಗಳು: ದೀರ್ಘಕಾಲದ ಹೊರಾಂಗಣ ಶ್ರಮವನ್ನು ಮಿತಿಗೊಳಿಸಿ.|ಭಾರೀ ಟ್ರಾಫಿಕ್ ಬಳಿ ವ್ಯಾಯಾಮ ಮಾಡಬೇಡಿ.",
    rec_sensitive_do: "ಆಸ್ತಮಾ/ಅಲರ್ಜಿ ಇದ್ದರೆ ಮಾಸ್ಕ್ ಧರಿಸಿ.|ಒಳಾಂಗಣದಲ್ಲಿ ಏರ್ ಪ್ಯೂರಿಫೈಯರ್‌ ಬಳಸಿ.|ಹೊರಾಂಗಣ ವ್ಯಾಯಾಮದ ತೀವ್ರತೆಯನ್ನು 50% ಕಡಿಮೆ ಮಾಡಿ.|ಉಸಿರಾಟದ ಸಮಸ್ಯೆಯಿದ್ದರೆ ಔಷಧಿ ಇಟ್ಟುಕೊಳ್ಳಿ.",
    rec_sensitive_dont: "ಉಸಿರಾಟದ ತೊಂದರೆ ಇದ್ದರೆ ಜಾಗಿಂಗ್ ಮಾಡಬೇಡಿ.|ಕಿಟಕಿಗಳನ್ನು ದೀರ್ಘಕಾಲ ತೆರೆದಿಡಬೇಡಿ.|ಮಕ್ಕಳು ಮತ್ತು ಹಿರಿಯರು ಹೊರಗೆ ಹೋಗುವುದನ್ನು ಮಿತಿಗೊಳಿಸಿ.",
    rec_unhealthy_do: "ಹೊರಗೆ ಹೋಗುವಾಗ N95/KN95 ಮಾಸ್ಕ್ ಧರಿಸಿ.|ಎಲ್ಲಾ ಕಿಟಕಿ ಮತ್ತು ಬಾಗಿಲುಗಳನ್ನು ಮುಚ್ಚಿಡಿ.|ಏರ್ ಪ್ಯೂರಿಫೈಯರ್‌ಗಳನ್ನು ಹೆಚ್ಚಿನ ಸೆಟ್ಟಿಂಗ್‌ನಲ್ಲಿ ಬಳಸಿ.|ಹೊರಗಿರಲೇಬೇಕಾದರೆ ವಿರಾಮ ತೆಗೆದುಕೊಳ್ಳಿ.",
    rec_unhealthy_dont: "ಕಠಿಣ ಹೊರಾಂಗಣ ಚಟುವಟಿಕೆಗಳನ್ನು ತಪ್ಪಿಸಿ.|ಮೇಣದಬತ್ತಿ ಅಥವಾ ಅನಿಲ ಒಲೆಗಳನ್ನು ಬಳಸಬೇಡಿ.|ಮಕ್ಕಳನ್ನು ಹೊರಗೆ ಆಡಲು ಬಿಡಬೇಡಿ.|ವ್ಯಾಕ್ಯೂಮ್ ಕ್ಲೀನರ್ ಬಳಸಬೇಡಿ (ಧೂಳು ಏಳುತ್ತದೆ).",
    rec_hazardous_do: "ಮನೆಯಲ್ಲೇ ಇರಿ - ಆರೋಗ್ಯ ತುರ್ತುಸ್ಥಿತಿ.|ಕಿಟಕಿ/ಬಾಗಿಲ ಸಂದುಗಳನ್ನು ಒದ್ದೆ ಬಟ್ಟೆಯಿಂದ ಮುಚ್ಚಿ.|ಸಾಧ್ಯವಿದ್ದರೆ ಏರ್ ಪ್ಯೂರಿಫೈಯರ್‌ ಬಳಸಿ.|ಉಸಿರಾಟದ ತೊಂದರೆಗೆ ತಕ್ಷಣ ವೈದ್ಯರನ್ನು ಭೇಟಿ ಮಾಡಿ.",
    rec_hazardous_dont: "ಅತ್ಯಗತ್ಯವಿಲ್ಲದಿದ್ದರೆ ಹೊರಗೆ ಹೋಗಬೇಡಿ.|ವ್ಯಾಯಾಮ ಮಾಡಬೇಡಿ.|ಕಿಟಕಿಗಳನ್ನು ತೆರೆಯಬೇಡಿ.|ಎಕ್ಸಾಸ್ಟ್ ಫ್ಯಾನ್ ಬಳಸಬೇಡಿ.",
    // New ML & UI Keys
    initializingMLEngine: 'ML ಎಂಜಿನ್ ಪ್ರಾರಂಭವಾಗುತ್ತಿದೆ',
    loadingMLModels: 'XGBoost + Random Forest ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    trendImproving: 'ಸುಧಾರಿಸುತ್ತಿದೆ',
    trendWorsening: 'ಕೆಟ್ಟದಾಗುತ್ತಿದೆ',
    trendStable: 'ಸ್ಥಿರವಾಗಿದೆ',
    rainClearsPollutants: 'ಮಳೆ ಮಾಲಿನ್ಯವನ್ನು ತೆರವುಗೊಳಿಸುತ್ತದೆ',
    windDispersesParticles: 'ಗಾಳಿ ಕಣಗಳನ್ನು ಚದುರಿಸುತ್ತದೆ',
    fogTrapsPollutants: 'ಮಂಜು ಮಾಲಿನ್ಯವನ್ನು ಸಿಕ್ಕಿಸುತ್ತದೆ',
    clearSkyOzoneRisk: 'ತಿಳಿ ಆಕಾಶ = ಓಜೋನ್ ಅಪಾಯ',
    stableConditions: 'ಸ್ಥಿರ ಪರಿಸ್ಥಿತಿ',
    earlyMorning: 'ಬೆಳಿಗ್ಗೆ ಬೇಗ (6-8 AM)',
    morningOrEvening: 'ಬೆಳಿಗ್ಗೆ ಅಥವಾ ಸಂಜೆ',
    middayTime: 'ಮಧ್ಯಾಹ್ನ (11 AM - 3 PM)',
    anyTimeToday: 'ಇಂದು ಯಾವ ಸಮಯದಲ್ಲಾದರೂ',
    rain: 'ಮಳೆ',
};

// Spanish translations
const es: Translations = {
    appName: 'AirSense Pro',
    realTimeAirQuality: 'Calidad del Aire en Tiempo Real',
    gps: 'GPS',
    defaultLocation: 'Predeterminado',
    locateMe: 'Ubicarme',
    currentLocation: 'Ubicación actual',
    airQualityIndex: 'Índice de Calidad del Aire',
    good: 'Bueno',
    moderate: 'Moderado',
    unhealthyForSensitive: 'No saludable para sensibles',
    unhealthy: 'No saludable',
    veryUnhealthy: 'Muy no saludable',
    hazardous: 'Peligroso',
    healthMsgGood: '✨ ¡Gran día para actividades al aire libre!',
    healthMsgModerate: '👍 El aire es aceptable. Las personas sensibles deben tener cuidado.',
    healthMsgSensitive: '⚠️ Limite las actividades al aire libre si tiene asma.',
    healthMsgUnhealthy: '🚫 Todos deben reducir la exposición al exterior.',
    healthMsgHazardous: '⛔ ¡Quédese adentro! Condiciones de emergencia de salud.',
    weatherConditions: 'Condiciones Climáticas',
    humidity: 'humedad',
    wind: 'Viento',
    pressure: 'Presión',
    dry: 'Seco',
    comfort: 'Confortable',
    humid: 'Húmedo',
    particulateMatter: 'Material Particulado',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 Excelente aire para respirar',
    acceptableAir: '😐 Aceptable para la mayoría de las personas',
    wearMask: '😷 Considere usar mascarilla al aire libre',
    avoidOutdoor: '🚫 Evite actividades al aire libre',
    todayForecast: 'Pronóstico de Hoy',
    fiveDayForecast: 'Pronóstico AQI de 5 Días',
    settings: 'Configuración',
    help: 'Ayuda',
    analysis: 'Análisis',
    history: 'Historial',
    search: 'Buscar',
    searchPlaceholder: 'Buscar ciudad o ubicación...',
    liveData: 'En vivo',
    apiSources: '7 Fuentes API',
    updatedNow: 'Actualizado ahora',
    indianCities: 'Principales Ciudades de India',
    recommendations: 'Recomendaciones de Salud IA',
    whatToDo: 'Qué Hacer',
    whatToAvoid: 'Qué Evitar',
    mlInsights: 'Perspectivas ML',
    aiPowered: 'Potenciado por IA',
    gasLevels: 'Monitoreo de Niveles de Gas',
    selectLanguage: 'Seleccionar Idioma',
    backend: 'Backend',
    accuracy: 'Precisión',
    confidence: 'Confianza',
    aqiForecast: 'Pronóstico AQI',
    next1Hr: '+1 Hora',
    next6Hrs: '+6 Horas',
    next24Hrs: '+24 Horas',
    pollutionSources: 'Fuentes de Contaminación (EPA PMF)',
    primary: 'Principal',
    ensembleVersion: 'Ensemble ML',
    active: 'Activo',
    healthRiskTitle: 'Evaluación de Riesgo de Salud',
    riskLow: 'BAJO',
    riskModerate: 'MODERADO',
    riskHigh: 'ALTO',
    riskVeryHigh: 'MUY ALTO',
    riskHazardous: 'PELIGROSO',
    safe: 'Seguro',
    notSafe: 'No Recomendado',
    outdoor: 'Exterior',
    high: 'Alto',
    low: 'Bajo',
    aqiImpact: 'Impacto AQI',
    bestOutdoor: 'Mejor Exterior',
    weatherCorrelation: 'Correlación Clima-AQI por ML',
    cityMumbai: 'Bombay',
    cityDelhi: 'Delhi',
    cityBangalore: 'Bangalore',
    cityHyderabad: 'Hyderabad',
    cityAhmedabad: 'Ahmedabad',
    cityChennai: 'Chennai',
    cityKolkata: 'Calcuta',
    cityPune: 'Pune',
    cityLucknow: 'Lucknow',
    cityNagpur: 'Nagpur',
    cityKanpur: 'Kanpur',
    cityJaipur: 'Jaipur',
    weatherClear: 'Cielo despejado',
    weatherClouds: 'Nublado',
    weatherRain: 'Lluvia',
    weatherDrizzle: 'Llovizna',
    weatherThunderstorm: 'Tormenta',
    weatherSnow: 'Nieve',
    weatherMist: 'Neblina',
    weatherSmoke: 'Humo',
    weatherHaze: 'Bruma',
    weatherDust: 'Polvo',
    weatherFog: 'Niebla densa',
    weatherSand: 'Arena',
    weatherAsh: 'Ceniza',
    weatherSquall: 'Chubasco',
    weatherTornado: 'Tornado',
    rec_excellent_do: "¡Día perfecto para actividades al aire libre!|Abre las ventanas para ventilar.|Buen momento para correr o andar en bici.|Disfruta de picnics al aire libre.",
    rec_excellent_dont: "¡Sin restricciones - disfruta del aire fresco!",
    rec_moderate_do: "El público puede disfrutar actividades al aire libre.|Personas sensibles deben monitorear síntomas.|Mejor ejercitarse por la mañana o tarde.|Mantener purificadores de aire encendidos.",
    rec_moderate_dont: "Grupos sensibles: limitar esfuerzo prolongado al aire libre.|Evita ejercitarte cerca de tráfico pesado.",
    rec_sensitive_do: "Usa mascarilla si tienes asma o alergias.|Usa purificadores de aire en ajuste medio.|Reduce el ejercicio al aire libre en 50%.|Ten medicamentos a mano.",
    rec_sensitive_dont: "Evita correr al aire libre si sientes falta de aire.|No mantengas ventanas abiertas mucho tiempo.|Niños y ancianos limiten tiempo al aire libre.",
    rec_unhealthy_do: "Usa mascarilla N95/KN95 al salir.|Mantén ventanas y puertas cerradas.|Usa purificadores de aire en ajuste alto.|Toma descansos si debes estar afuera.",
    rec_unhealthy_dont: "Evita actividades extenuantes al aire libre.|No enciendas velas, incienso ni estufas de gas.|No dejes que niños jueguen afuera.|Evita aspirar (levanta polvo).",
    rec_hazardous_do: "QUÉDATE ADENTRO - emergencia de salud.|Sella huecos de ventanas con toallas húmedas.|Usa múltiples purificadores de aire.|Busca ayuda médica para problemas respiratorios.",
    rec_hazardous_dont: "NO salgas a menos que sea necesario.|No hagas ejercicio, ni siquiera adentro.|No abras ninguna ventana o puerta.|No uses extractores de aire exterior.",
    // New ML & UI Keys
    initializingMLEngine: 'Inicializando Motor ML',
    loadingMLModels: 'Cargando XGBoost + Random Forest...',
    trendImproving: 'Mejorando',
    trendWorsening: 'Empeorando',
    trendStable: 'Estable',
    rainClearsPollutants: 'La lluvia limpia contaminantes',
    windDispersesParticles: 'El viento dispersa partículas',
    fogTrapsPollutants: 'La niebla atrapa contaminantes',
    clearSkyOzoneRisk: 'Cielo despejado = riesgo de ozono',
    stableConditions: 'Condiciones estables',
    earlyMorning: 'Temprano (6-8 AM)',
    morningOrEvening: 'Mañana o tarde',
    middayTime: 'Mediodía (11 AM - 3 PM)',
    anyTimeToday: 'Cualquier hora hoy',
    rain: 'Lluvia',
};

// French translations
const fr: Translations = {
    appName: 'AirSense Pro',
    realTimeAirQuality: "Qualité de l'Air en Temps Réel",
    gps: 'GPS',
    defaultLocation: 'Par défaut',
    locateMe: 'Me localiser',
    currentLocation: 'Position actuelle',
    airQualityIndex: "Indice de Qualité de l'Air",
    good: 'Bon',
    moderate: 'Modéré',
    unhealthyForSensitive: 'Malsain pour les sensibles',
    unhealthy: 'Malsain',
    veryUnhealthy: 'Très malsain',
    hazardous: 'Dangereux',
    healthMsgGood: '✨ Excellente journée pour les activités de plein air!',
    healthMsgModerate: "👍 L'air est acceptable. Les personnes sensibles doivent faire attention.",
    healthMsgSensitive: '⚠️ Limitez les activités extérieures si vous avez de l\'asthme.',
    healthMsgUnhealthy: '🚫 Tout le monde devrait réduire l\'exposition extérieure.',
    healthMsgHazardous: '⛔ Restez à l\'intérieur! Conditions d\'urgence sanitaire.',
    weatherConditions: 'Conditions Météorologiques',
    humidity: 'humidité',
    wind: 'Vent',
    pressure: 'Pression',
    dry: 'Sec',
    comfort: 'Confort',
    humid: 'Humide',
    particulateMatter: 'Matière Particulaire',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 Excellent air pour respirer',
    acceptableAir: '😐 Acceptable pour la plupart des gens',
    wearMask: '😷 Envisagez de porter un masque à l\'extérieur',
    avoidOutdoor: '🚫 Évitez les activités de plein air',
    todayForecast: "Prévisions d'Aujourd'hui",
    fiveDayForecast: 'Prévisions AQI sur 5 Jours',
    settings: 'Paramètres',
    help: 'Aide',
    analysis: 'Analyse',
    history: 'Historique',
    search: 'Rechercher',
    searchPlaceholder: 'Rechercher ville ou emplacement...',
    liveData: 'En direct',
    apiSources: '7 Sources API',
    updatedNow: 'Mis à jour maintenant',
    indianCities: 'Principales Villes Indiennes',
    recommendations: 'Recommandations Santé IA',
    whatToDo: 'Quoi Faire',
    whatToAvoid: 'Quoi Éviter',
    mlInsights: 'Insights ML',
    aiPowered: 'Propulsé par IA',
    gasLevels: 'Surveillance des Niveaux de Gaz',
    selectLanguage: 'Sélectionner la Langue',
    backend: 'Backend',
    accuracy: 'Précision',
    confidence: 'Confiance',
    aqiForecast: 'Prévision AQI',
    next1Hr: '+1 Heure',
    next6Hrs: '+6 Heures',
    next24Hrs: '+24 Heures',
    pollutionSources: 'Sources de Pollution (EPA PMF)',
    primary: 'Principal',
    ensembleVersion: 'Ensemble ML',
    active: 'Actif',
    healthRiskTitle: 'Évaluation du Risque Santé',
    riskLow: 'FAIBLE',
    riskModerate: 'MODÉRÉ',
    riskHigh: 'ÉLEVÉ',
    riskVeryHigh: 'TRÈS ÉLEVÉ',
    riskHazardous: 'DANGEREUX',
    safe: 'Sûr',
    notSafe: 'Non Recommandé',
    outdoor: 'Extérieur',
    high: 'Élevé',
    low: 'Faible',
    aqiImpact: 'Impact AQI',
    bestOutdoor: 'Meilleur Extérieur',
    weatherCorrelation: 'Corrélation Météo-AQI par ML',
    cityMumbai: 'Bombay',
    cityDelhi: 'Delhi',
    cityBangalore: 'Bangalore',
    cityHyderabad: 'Hyderabad',
    cityAhmedabad: 'Ahmedabad',
    cityChennai: 'Chennai',
    cityKolkata: 'Calcutta',
    cityPune: 'Pune',
    cityLucknow: 'Lucknow',
    cityNagpur: 'Nagpur',
    cityKanpur: 'Kanpur',
    cityJaipur: 'Jaipur',
    weatherClear: 'Ciel dégagé',
    weatherClouds: 'Nuageux',
    weatherRain: 'Pluie',
    weatherDrizzle: 'Bruine',
    weatherThunderstorm: 'Orage',
    weatherSnow: 'Neige',
    weatherMist: 'Brume',
    weatherSmoke: 'Fumée',
    weatherHaze: 'Brouillard léger',
    weatherDust: 'Poussière',
    weatherFog: 'Brouillard dense',
    weatherSand: 'Sable',
    weatherAsh: 'Cendres',
    weatherSquall: 'Rafale',
    weatherTornado: 'Tornade',
    rec_excellent_do: "Journée parfaite pour les activités extérieures!|Ouvrez les fenêtres pour aérer.|Bon moment pour courir ou faire du vélo.|Profitez des pique-niques en plein air.",
    rec_excellent_dont: "Aucune restriction - profitez de l'air frais!",
    rec_moderate_do: "Le public peut profiter des activités extérieures.|Les personnes sensibles doivent surveiller les symptômes.|Préférable de faire de l'exercice le matin ou le soir.|Gardez les purificateurs d'air en marche.",
    rec_moderate_dont: "Groupes sensibles: limiter les efforts prolongés à l'extérieur.|Évitez l'exercice près des zones de circulation dense.",
    rec_sensitive_do: "Portez un masque si vous avez de l'asthme ou des allergies.|Purificateurs d'air sur réglage moyen.|Réduisez l'intensité de l'exercice extérieur de 50%.|Gardez vos médicaments à portée de main.",
    rec_sensitive_dont: "Évitez le jogging extérieur si essoufflé.|Ne laissez pas les fenêtres ouvertes trop longtemps.|Enfants et personnes âgées: limitez le temps à l'extérieur.",
    rec_unhealthy_do: "Portez un masque N95/KN95 en sortant.|Gardez fenêtres et portes fermées.|Purificateurs d'air sur réglage élevé.|Faites des pauses si vous devez être dehors.",
    rec_unhealthy_dont: "Évitez les activités intenses à l'extérieur.|N'allumez pas bougies, encens ou cuisinières à gaz.|Ne laissez pas les enfants jouer dehors.|Évitez l'aspirateur (soulève la poussière).",
    rec_hazardous_do: "RESTEZ À L'INTÉRIEUR - urgence sanitaire.|Scellez les interstices avec des serviettes humides.|Utilisez plusieurs purificateurs d'air.|Consultez un médecin pour problèmes respiratoires.",
    rec_hazardous_dont: "NE SORTEZ PAS sauf nécessité absolue.|Pas d'exercice, même à l'intérieur.|N'ouvrez aucune fenêtre ni porte.|N'utilisez pas de ventilateurs extracteurs.",
    // New ML & UI Keys
    initializingMLEngine: 'Initialisation du Moteur ML',
    loadingMLModels: 'Chargement de XGBoost + Random Forest...',
    trendImproving: 'En amélioration',
    trendWorsening: 'En détérioration',
    trendStable: 'Stable',
    rainClearsPollutants: 'La pluie élimine les polluants',
    windDispersesParticles: 'Le vent disperse les particules',
    fogTrapsPollutants: 'Le brouillard piège les polluants',
    clearSkyOzoneRisk: 'Ciel dégagé = risque ozone',
    stableConditions: 'Conditions stables',
    earlyMorning: 'Tôt le matin (6-8h)',
    morningOrEvening: 'Matin ou soir',
    middayTime: 'Midi (11h - 15h)',
    anyTimeToday: "N'importe quand aujourd'hui",
    rain: 'Pluie',
};

// Chinese translations
const zh: Translations = {
    appName: 'AirSense Pro',
    realTimeAirQuality: '实时空气质量',
    gps: 'GPS',
    defaultLocation: '默认',
    locateMe: '定位我',
    currentLocation: '当前位置',
    airQualityIndex: '空气质量指数',
    good: '良好',
    moderate: '中等',
    unhealthyForSensitive: '敏感人群不健康',
    unhealthy: '不健康',
    veryUnhealthy: '非常不健康',
    hazardous: '危险',
    healthMsgGood: '✨ 户外活动的好日子！',
    healthMsgModerate: '👍 空气可接受。敏感人群请注意。',
    healthMsgSensitive: '⚠️ 如果有哮喘，请限制户外活动。',
    healthMsgUnhealthy: '🚫 每个人都应该减少户外暴露。',
    healthMsgHazardous: '⛔ 待在室内！健康紧急情况。',
    weatherConditions: '天气状况',
    humidity: '湿度',
    wind: '风速',
    pressure: '气压',
    dry: '干燥',
    comfort: '舒适',
    humid: '潮湿',
    particulateMatter: '颗粒物',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 呼吸的绝佳空气',
    acceptableAir: '😐 大多数人可接受',
    wearMask: '😷 考虑在户外戴口罩',
    avoidOutdoor: '🚫 避免户外活动',
    todayForecast: '今日预报',
    fiveDayForecast: '5天AQI预报',
    settings: '设置',
    help: '帮助',
    analysis: '分析',
    history: '历史',
    search: '搜索',
    searchPlaceholder: '搜索城市或位置...',
    liveData: '实时',
    apiSources: '7个API来源',
    updatedNow: '刚刚更新',
    indianCities: '印度主要城市',
    recommendations: 'AI健康建议',
    whatToDo: '做什么',
    whatToAvoid: '避免什么',
    mlInsights: 'ML洞察',
    aiPowered: 'AI驱动',
    gasLevels: '气体水平监测',
    selectLanguage: '选择语言',
    backend: '后端',
    accuracy: '准确度',
    confidence: '置信度',
    aqiForecast: 'AQI预测',
    next1Hr: '+1小时',
    next6Hrs: '+6小时',
    next24Hrs: '+24小时',
    pollutionSources: '污染源 (EPA PMF)',
    primary: '主要',
    ensembleVersion: 'Ensemble ML',
    active: '运行中',
    healthRiskTitle: '健康风险评估',
    riskLow: '低',
    riskModerate: '中等',
    riskHigh: '高',
    riskVeryHigh: '非常高',
    riskHazardous: '危险',
    safe: '安全',
    notSafe: '不推荐',
    outdoor: '户外',
    high: '高',
    low: '低',
    aqiImpact: 'AQI影响',
    bestOutdoor: '最佳户外',
    weatherCorrelation: 'ML 天气-AQI 关联分析',
    cityMumbai: '孟买',
    cityDelhi: '德里',
    cityBangalore: '班加罗尔',
    cityHyderabad: '海德拉巴德',
    cityAhmedabad: '艾哈迈达巴德',
    cityChennai: '金奈',
    cityKolkata: '加尔各答',
    cityPune: '浦那',
    cityLucknow: '勒克瑙',
    cityNagpur: '那格浦尔',
    cityKanpur: '坎普尔',
    cityJaipur: '斋浦尔',
    weatherClear: '晴朗',
    weatherClouds: '多云',
    weatherRain: '雨',
    weatherDrizzle: '毛毛雨',
    weatherThunderstorm: '雷暴雨',
    weatherSnow: '雪',
    weatherMist: '薄雾',
    weatherSmoke: '烟雾',
    weatherHaze: '霾霾',
    weatherDust: '灰尘',
    weatherFog: '浓雾',
    weatherSand: '沙尘',
    weatherAsh: '火山灰',
    weatherSquall: '飑风',
    weatherTornado: '龙卷风',
    rec_excellent_do: "户外活动的绝佳日子！|打开窗户通风。|跑步、骑车的好时机。|享受野餐和户外聚会。",
    rec_excellent_dont: "没有限制 - 享受新鲜空气！",
    rec_moderate_do: "普通人群可以享受户外活动。|敏感人群应监测症状。|早晚锻炼最佳。|保持室内空气净化器运行。",
    rec_moderate_dont: "敏感人群：限制长时间户外活动。|避免在交通拥挤区域锻炼。",
    rec_sensitive_do: "哮喘/过敏者佩戴口罩。|空气净化器调至中档。|户外运动强度减半。|呼吸问题者备好药物。",
    rec_sensitive_dont: "呼吸困难时勿户外跑步。|不要长时间开窗。|儿童和老人应减少户外时间。",
    rec_unhealthy_do: "外出时佩戴N95/KN95口罩。|关闭所有门窗。|空气净化器调至高档。|必须外出时适时休息。",
    rec_unhealthy_dont: "避免所有剧烈户外活动。|不要点蜡烛、熏香或使用燃气炉。|不要让孩子在外玩耍。|避免使用吸尘器（会扬尘）。",
    rec_hazardous_do: "待在室内 - 健康紧急状况。|用湿毛巾封住门窗缝隙。|尽量多开空气净化器。|呼吸问题立即就医。",
    rec_hazardous_dont: "非绝对必要勿外出。|室内也不要运动。|不要打开任何门窗。|不要使用吸入外部空气的排风扇。",
    // New ML & UI Keys
    initializingMLEngine: '正在初始化ML引擎',
    loadingMLModels: '正在加载XGBoost + 随机森林...',
    trendImproving: '改善中',
    trendWorsening: '恶化中',
    trendStable: '稳定',
    rainClearsPollutants: '降雨清除污染物',
    windDispersesParticles: '风吹散颗粒物',
    fogTrapsPollutants: '雾霾困住污染物',
    clearSkyOzoneRisk: '晴天 = 臭氧风险',
    stableConditions: '条件稳定',
    earlyMorning: '清晨 (6-8点)',
    morningOrEvening: '上午或傍晚',
    middayTime: '中午 (11点 - 3点)',
    anyTimeToday: '今天任何时间',
    rain: '雨',
};

// Arabic translations
const ar: Translations = {
    appName: 'ايرسينس برو',
    realTimeAirQuality: 'جودة الهواء في الوقت الحقيقي',
    gps: 'جي بي إس',
    defaultLocation: 'افتراضي',
    locateMe: 'حدد موقعي',
    currentLocation: 'الموقع الحالي',
    airQualityIndex: 'مؤشر جودة الهواء',
    good: 'جيد',
    moderate: 'معتدل',
    unhealthyForSensitive: 'غير صحي للحساسين',
    unhealthy: 'غير صحي',
    veryUnhealthy: 'غير صحي جداً',
    hazardous: 'خطر',
    healthMsgGood: '✨ يوم رائع للأنشطة الخارجية!',
    healthMsgModerate: '👍 الهواء مقبول. الأشخاص الحساسون يجب أن يحذروا.',
    healthMsgSensitive: '⚠️ قلل الأنشطة الخارجية إذا كان لديك ربو.',
    healthMsgUnhealthy: '🚫 يجب على الجميع تقليل التعرض للخارج.',
    healthMsgHazardous: '⛔ ابق في الداخل! حالة طوارئ صحية.',
    weatherConditions: 'حالة الطقس',
    humidity: 'الرطوبة',
    wind: 'الرياح',
    pressure: 'الضغط',
    dry: 'جاف',
    comfort: 'مريح',
    humid: 'رطب',
    particulateMatter: 'الجسيمات الدقيقة',
    fine: 'PM2.5',
    coarse: 'PM10',
    excellentAir: '😊 هواء ممتاز للتنفس',
    acceptableAir: '😐 مقبول لمعظم الناس',
    wearMask: '😷 فكر في ارتداء قناع في الخارج',
    avoidOutdoor: '🚫 تجنب الأنشطة الخارجية',
    todayForecast: 'توقعات اليوم',
    fiveDayForecast: 'توقعات AQI لـ 5 أيام',
    settings: 'الإعدادات',
    help: 'المساعدة',
    analysis: 'التحليل',
    history: 'التاريخ',
    search: 'بحث',
    searchPlaceholder: 'ابحث عن مدينة أو موقع...',
    liveData: 'مباشر',
    apiSources: '7 مصادر API',
    updatedNow: 'تم التحديث للتو',
    indianCities: 'المدن الهندية الكبرى',
    recommendations: 'توصيات صحية بالذكاء الاصطناعي',
    whatToDo: 'ماذا تفعل',
    whatToAvoid: 'ماذا تتجنب',
    mlInsights: 'رؤى ML',
    aiPowered: 'مدعوم بالذكاء الاصطناعي',
    gasLevels: 'مراقبة مستويات الغاز',
    selectLanguage: 'اختر اللغة',
    backend: 'الخلفية',
    accuracy: 'الدقة',
    confidence: 'الثقة',
    aqiForecast: 'توقعات AQI',
    next1Hr: '+١ ساعة',
    next6Hrs: '+٦ ساعات',
    next24Hrs: '+٢٤ ساعة',
    pollutionSources: 'مصادر التلوث (EPA PMF)',
    primary: 'رئيسي',
    ensembleVersion: 'Ensemble ML',
    active: 'نشط',
    healthRiskTitle: 'تقييم المخاطر الصحية',
    riskLow: 'منخفض',
    riskModerate: 'متوسط',
    riskHigh: 'مرتفع',
    riskVeryHigh: 'مرتفع جداً',
    riskHazardous: 'خطير',
    safe: 'آمن',
    notSafe: 'غير موصى به',
    outdoor: 'خارجي',
    high: 'مرتفع',
    low: 'منخفض',
    aqiImpact: 'تأثير AQI',
    bestOutdoor: 'أفضل وقت',
    weatherCorrelation: 'ارتباط الطقس-AQI بواسطة ML',
    cityMumbai: 'مومباي',
    cityDelhi: 'نيودلهي',
    cityBangalore: 'بنغالور',
    cityHyderabad: 'حيدر آباد',
    cityAhmedabad: 'أحمد آباد',
    cityChennai: 'شيناي',
    cityKolkata: 'كولكاتا',
    cityPune: 'بونا',
    cityLucknow: 'لكنو',
    cityNagpur: 'ناغبور',
    cityKanpur: 'كانبور',
    cityJaipur: 'جايبور',
    weatherClear: 'سماء صافية',
    weatherClouds: 'غائم',
    weatherRain: 'مطر',
    weatherDrizzle: 'رذاذ',
    weatherThunderstorm: 'عاصفة رعدية',
    weatherSnow: 'ثلج',
    weatherMist: 'ضباب خفيف',
    weatherSmoke: 'دخان',
    weatherHaze: 'غبار',
    weatherDust: 'غبار',
    weatherFog: 'ضباب كثيف',
    weatherSand: 'رمل',
    weatherAsh: 'رماد',
    weatherSquall: 'عاصفة',
    weatherTornado: 'إعصار',
    rec_excellent_do: "يوم مثالي للأنشطة الخارجية!|افتح النوافذ للتهوية.|وقت رائع للجري وركوب الدراجات.|استمتع بالنزهات والتجمعات.",
    rec_excellent_dont: "لا قيود - استمتع بالهواء النقي!",
    rec_moderate_do: "يمكن للعامة الاستمتاع بالأنشطة الخارجية.|يجب على الحساسين مراقبة الأعراض.|الأفضل ممارسة الرياضة صباحاً أو مساءً.|أبقِ أجهزة تنقية الهواء عاملة.",
    rec_moderate_dont: "المجموعات الحساسة: قلل من المجهود الخارجي المطوّل.|تجنب التمارين بالقرب من المناطق المزدحمة.",
    rec_sensitive_do: "ارتدِ كمامة إذا كنت مصاباً بالربو/الحساسية.|شغّل أجهزة تنقية الهواء على الوضع المتوسط.|قلل شدة التمارين الخارجية بنسبة 50%.|احتفظ بالأدوية في متناول اليد.",
    rec_sensitive_dont: "تجنب الركض الخارجي إذا شعرت بضيق التنفس.|لا تبقِ النوافذ مفتوحة لفترات طويلة.|يجب على الأطفال وكبار السن تقليل الوقت في الخارج.",
    rec_unhealthy_do: "ارتدِ كمامة N95/KN95 عند الخروج.|أغلق جميع النوافذ والأبواب.|شغّل أجهزة تنقية الهواء على الوضع العالي.|خذ فترات راحة إذا كان يجب أن تكون في الخارج.",
    rec_unhealthy_dont: "تجنب جميع الأنشطة الشاقة في الخارج.|لا تشعل الشموع أو البخور أو مواقد الغاز.|لا تدع الأطفال يلعبون في الخارج.|تجنب الكنس بالمكنسة الكهربائية (يثير الغبار).",
    rec_hazardous_do: "ابقَ في الداخل - حالة طوارئ صحية.|أغلق فتحات النوافذ والأبواب بمناشف مبللة.|شغّل عدة أجهزة تنقية هواء إن أمكن.|اطلب المساعدة الطبية فوراً لمشاكل التنفس.",
    rec_hazardous_dont: "لا تخرج إلا للضرورة القصوى.|لا تمارس الرياضة إطلاقاً، حتى في الداخل.|لا تفتح أي نوافذ أو أبواب.|لا تستخدم مراوح الشفط التي تجلب الهواء الخارجي.",
    // New ML & UI Keys
    initializingMLEngine: 'جارٍ تهيئة محرك ML',
    loadingMLModels: 'جارٍ تحميل XGBoost + Random Forest...',
    trendImproving: 'يتحسن',
    trendWorsening: 'يتدهور',
    trendStable: 'مستقر',
    rainClearsPollutants: 'المطر ينظف الملوثات',
    windDispersesParticles: 'الرياح تفرق الجسيمات',
    fogTrapsPollutants: 'الضباب يحبس الملوثات',
    clearSkyOzoneRisk: 'سماء صافية = خطر الأوزون',
    stableConditions: 'ظروف مستقرة',
    earlyMorning: 'الصباح الباكر (6-8 ص)',
    morningOrEvening: 'صباحاً أو مساءً',
    middayTime: 'منتصف اليوم (11 ص - 3 م)',
    anyTimeToday: 'أي وقت اليوم',
    rain: 'مطر',
};

// All translations
const translations: Record<LanguageCode, Translations> = {
    en, hi, ta, te, bn, mr, kn, es, fr, zh, ar
};

// Context
interface LanguageContextType {
    language: LanguageCode;
    setLanguage: (lang: LanguageCode) => void;
    t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'airsense_language';

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<LanguageCode>(() => {
        try {
            const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
            if (saved && saved in LANGUAGES) {
                return saved as LanguageCode;
            }
        } catch (e) {
            // localStorage not available
        }
        return 'en';
    });

    const setLanguage = (lang: LanguageCode) => {
        setLanguageState(lang);
        try {
            localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
        } catch (e) {
            // localStorage not available
        }
    };

    useEffect(() => {
        // Set HTML dir attribute for RTL languages
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export default translations;
